#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
institucional_datos.py — codificación manual del canal institucional (PROTOCOLO § 9.3; docs/canales/codigos_institucional.md).

Un solo codificador (enmienda 6). Cada aparición de results/canales/institucional_apariciones.csv se codifica en su
contexto con (uso, rasgos, juicio, nota). Las claves son (documento, referencia, término) y, cuando dos apariciones de
la misma referencia y término se codifican distinto, (documento, referencia, término, forma). Lo que no está en CODIGOS
lo cubren las reglas por defecto de institucional_codificar.py (que se declaran allí).

PARALELOS: comparación externa § 4 (AGRW, consultas 172-191 de docs/canales/registro_consultas.md) y, para lo que las
asociaciones no documentan, el texto más antiguo del corpus § 2 (§ 6.3 del libro de códigos).
"""

# ---------------------------------------------------------------------------------------------------------------------
# Paralelos: (término o rasgo) → (fase, origen, fuente, cita)
# fase: s1 / fin_s1 / s2; origen: asociaciones / corpus_cristiano
# ---------------------------------------------------------------------------------------------------------------------
PARALELOS = {
    # cargos
    ("ἐπίσκοπος", "cargo"): ("s1", "asociaciones", "IG XII,3 329 (Thera, ca. 200 a. C.; AGRW ID 12910); IRhodPC 2 (Rodas, s. II a. C.; AGRW ID 14975); IDelos 1522 (Delos, 98-117; AGRW ID 21076)",
                              "τὸς ἐπισκό[πος] Δίωνα καὶ Μελέϊππον: dos «supervisores» del koinón prestan a interés el legado (Thera); ἐπὶ … Ζή]νωνος ἐπισκόπου, epónimo (Rodas); τὸν ἐπίσκοπον, encargado de la copia del decreto y multado si no cumple (Delos)"),
    ("πρεσβύτερος", "cargo"): ("s1", "asociaciones", "OGIS II 729 = SB V 8924 (Alejandría, 221-205 a. C.; GRA III 155); SEG 42.1312 (Kition, ca. 250-200 a. C.); PSI VIII 901 (Tebtynis, 46; GRA III 218); IFayum II 122 (Theadelphia, 109; GRA III 229)",
                                "οἱ πρεσβύτεροι τῶν ὀλυροκόπων (Alejandría); τὸν θίασον τῶν πρεσβυτέρων (Kition); οἱ δεκατρεῖς πρεσβύτεροι ἁλιέων (Tebtynis, 46 d. C.); πρεσβύτεροι de los tejedores (Theadelphia, 109)"),
    ("διάκονος", "cargo"): ("s1", "asociaciones", "RICIS 111/0102 = CIG II 1800 (Ambracia, s. I a. C.; AGRW ID 23778); IBeroia 26 (Berea, ca. 100-150; AGRW 36)",
                             "τὸ κοινὸν τῶν διακόνων Σαράπει, Ἴσει, Ἀνούβει, Ἁρποκράτει, con sacerdote y lista de miembros (Ambracia); Π. Κορνήλιος Ῥοῦφος καὶ οἱ ὑπ’ αὐτὸν διάκονοι (Berea)"),
    ("προϊστάμενος", "cargo"): ("s1", "asociaciones", "PMich V 243 (Tebtynis, 14-37; AGRW 300); IG II² 1284 (Pireo, 241/240 a. C.; AGRW 17)",
                                 "ἐξέστω τῷ προστάτῃ ἐνεχυράζειν: el προστάτης de la asociación ejecuta las multas; κύριος τῷ προστάτῃ ἀποδοθήτω (Tebtynis)"),
    ("ἡγούμενος", "cargo"): ("s1", "asociaciones", "PLond VII 2193 (Filadelfia, 69-58 a. C.; AGRW 295); PMich V 244 (Tebtynis, 43; AGRW 301)",
                              "προχειρισάμενοι ἐπ’ ἑαυτῶν ἡγούμενον Πετεσοῦχον …, ἄνδρα λόγιον, τοῦ τόπου καὶ τῶν ἀνδρῶν ἄξιον, εἰς ἐνιαυτόν (Filadelfia); πάντας ἐνακούειν τῷ αὐτῷ ἡγουμένῳ … ἐξεῖναι τῷ αὐτῷ ἡγουμένῳ ἐνεχυράζειν (Tebtynis)"),
    # categorías
    ("χήρα", "categoria"): ("fin_s1", "corpus_cristiano", "AGRW: χήρα solo como estado civil (Termessos, s. II: honores a Atalante); ningún grupo de viudas en asociaciones. Corpus § 2: Hch 6,1 (αἱ χῆραι en la διακονία καθημερινή); Hch 9,39-41",
                            "las viudas como grupo reconocido de la comunidad aparecen por primera vez en Hechos (fecha convencional 80-90)"),
    ("νεώτερος", "categoria"): ("fin_s1", "corpus_cristiano", "AGRW: νεώτερος solo como sobrenombre («el joven») en listas de miembros; los νέοι son grupo cívico del gimnasio, no de asociación. Corpus § 2: Hch 5,6 (οἱ νεώτεροι); Policarpo 5,3",
                                "los jóvenes como grupo de la comunidad aparecen por primera vez en Hechos (fecha convencional 80-90)"),
    # ritos
    ("ἐπίθεσις χειρῶν", "rito"): ("fin_s1", "corpus_cristiano", "sin equivalente en asociaciones (§ 4). Corpus § 2: Hch 6,6 (los Siete); 13,3 (envío de Bernabé y Saulo); 8,17-19; 19,6",
                                   "imposición de manos como rito de institución o de transmisión del Espíritu: primera atestación en Hechos (80-90)"),
    ("χειροτονία", "rito"): ("s1", "asociaciones", "IDelos 1520 (Delos, ca. 150 a. C.; AGRW 224); IRhamnous II 59 (Ramnunte, después de 216/215 a. C.; GRA I 27); PLond VII 2193 (AGRW 295)",
                             "τοῖς ἐπὶ τὴν κατασκευὴν τοῦ τεμένους χειροτονηθεῖσιν; τῶν χειροτονηθέντων βουτρόφων: encargados elegidos por el koinón (Delos); προχειρισάμενοι … ἡγούμενον (Filadelfia)"),
    # rasgos
    ("rasgo", "requisitos"): ("s1", "asociaciones", "PLond VII 2193 (AGRW 295, 69-58 a. C.); IG XII,3 330 (Thera, 210-195 a. C.; AGRW 243)",
                              "ἄνδρα λόγιον, τοῦ τόπου καὶ τῶν ἀνδρῶν ἄξιον: cualidades exigidas al ἡγούμενος (Filadelfia)"),
    ("rasgo", "eleccion"): ("s1", "asociaciones", "IDelos 1520 (AGRW 224); PLond VII 2193 (AGRW 295)",
                            "χειροτονηθέντες / προχειρισάμενοι: elección por la asociación, anual (Filadelfia)"),
    ("rasgo", "remuneracion"): ("s1", "asociaciones", "IDelta I 446 (Psenamosis, 67 y 64 a. C.; AGRW 287)",
                                "λαμβάνειν διπλᾶ μέρη: doble porción para el sacerdote vitalicio honrado; exención de cuotas"),
    ("rasgo", "disciplina"): ("s1", "asociaciones", "PMich V 243 (AGRW 300, 14-37); PMich V 244 (AGRW 301, 43); IG XII,3 330 (AGRW 243)",
                              "ζημιούσθω … ἐξέστω τῷ προστάτῃ ἐνεχυράζειν: multas y embargo por el presidente"),
    ("rasgo", "jerarquia"): ("s1", "asociaciones", "PMich V 244 (AGRW 301, 43)",
                             "πάντας ἐνακούειν τῷ αὐτῷ ἡγουμένῳ: obediencia de todos al ἡγούμενος, que además nombra al ἐπιμελητής (Cronión) — subordinación explícita entre funciones"),
    ("rasgo", "monoepiscopado"): ("s2", "corpus_cristiano", "sin paralelo en asociaciones (un solo ἐπίσκοπος distinto del colegio de πρεσβύτεροι). Corpus § 2: Ignacio (Ef 1,3; Magn 2,1; 6,1; Tral 2,2-3,1; Fil 4,1; Esm 8,1-2); ausente de Hechos, 1 Clemente y Didajé (control negativo)",
                                  "εἷς ἐπίσκοπος ἅμα τῷ πρεσβυτερίῳ καὶ διακόνοις (IgnFil 4,1): primera atestación, Ignacio (ca. 110)"),
    ("rasgo", "colegio"): ("s1", "asociaciones", "IG XII,3 329 (Thera, ca. 200 a. C.); OGIS II 729 (Alejandría, 221-205 a. C.)",
                           "τὸς ἐπισκό[πος] Δίωνα καὶ Μελέϊππον (dos); οἱ πρεσβύτεροι τῶν ὀλυροκόπων (seis nombres)"),
    ("rasgo", "registro"): ("s1", "asociaciones", "PMich V 243-244 (AGRW 300-301, 14-43): listas de miembros con edad y señas (ὡς ἐτῶν μβ, οὐλὴ…); AGRW «Membership List with Physical Descriptions» (Tebtynis, 40/41)",
                            "listas nominales de miembros con edad: el registro de una categoría con requisito de edad tiene paralelo formal en las asociaciones (juicio)"),
    ("rasgo", "sucesion"): ("fin_s1", "corpus_cristiano", "sin paralelo en asociaciones (la sucesión en el cargo es por elección anual). Corpus § 2: 1 Clem 44,1-2",
                            "ἐπινομὴν δεδώκασιν ὅπως … διαδέξωνται ἕτεροι δεδοκιμασμένοι ἄνδρες τὴν λειτουργίαν αὐτῶν: 1 Clemente (96)"),
}

# ---------------------------------------------------------------------------------------------------------------------
# Codificación de las apariciones: (documento, ref, término[, forma]) → (uso, rasgos, juicio, nota)
# uso: cargo / funcion / categoria / celula / reunion / local / universal / rito / no_institucional
# ---------------------------------------------------------------------------------------------------------------------
NI = "no_institucional"
CODIGOS = {
    # ===== Romanos =====
    ("Rom", "11:13", "διάκονος"): ("funcion", "", "no", "διακονία apostólica de Pablo"),
    ("Rom", "12:7", "διάκονος"): ("funcion", "", "no", "διακονία entre los carismas (Rom 12,6-8), sin título"),
    ("Rom", "12:8", "προϊστάμενος"): ("funcion", "", "no", "ὁ προϊστάμενος entre los carismas, sin título"),
    ("Rom", "13:4", "διάκονος"): (NI, "", "no", "la autoridad civil como διάκονος de Dios"),
    ("Rom", "15:8", "διάκονος"): (NI, "", "no", "Cristo διάκονος de la circuncisión"),
    ("Rom", "15:25", "διάκονος"): ("funcion", "", "no", "la colecta para Jerusalén"),
    ("Rom", "15:31", "διάκονος"): ("funcion", "", "no", "la colecta para Jerusalén"),
    ("Rom", "16:1", "διάκονος"): ("cargo", "", "sí", "Febe, διάκονος τῆς ἐκκλησίας τῆς ἐν Κεγχρεαῖς: título con iglesia local; sin requisitos ni elección (juicio: cargo o función)"),
    ("Rom", "16:2", "προϊστάμενος"): ("funcion", "", "sí", "προστάτις πολλῶν: patrona; paralelo del προστάτης de las asociaciones, pero aquí sin cargo"),
    ("Rom", "16:1", "ἐκκλησία"): ("local", "", "no", "la iglesia de Cencreas"),
    ("Rom", "16:4", "ἐκκλησία"): ("local", "", "no", "todas las iglesias de los gentiles (plural de comunidades)"),
    ("Rom", "16:5", "οἶκος"): ("celula", "", "no", "ἡ κατ’ οἶκον αὐτῶν ἐκκλησία (Prisca y Aquila)"),
    ("Rom", "16:5", "ἐκκλησία"): ("local", "", "no", "iglesia doméstica"),
    ("Rom", "16:16", "ἐκκλησία"): ("local", "", "no", "αἱ ἐκκλησίαι πᾶσαι τοῦ Χριστοῦ"),
    ("Rom", "16:23", "ἐκκλησία"): ("local", "", "no", "Gayo, hospedador de toda la iglesia (Corinto)"),
    # ===== 1 Corintios =====
    ("1Cor", "1:2", "ἐκκλησία"): ("local", "", "no", "prescripto"),
    ("1Cor", "1:16", "οἶκος"): ("celula", "", "no", "bautismo de la casa de Estéfanas"),
    ("1Cor", "3:5", "διάκονος"): ("funcion", "", "no", "Pablo y Apolo διάκονοι"),
    ("1Cor", "4:17", "ἐκκλησία"): ("local", "", "no", "ἐν πάσῃ ἐκκλησίᾳ"),
    ("1Cor", "6:4", "ἐκκλησία"): ("local", "", "no", "tribunales dentro de la comunidad"),
    ("1Cor", "7:8", "χήρα"): (NI, "", "no", "estado civil"),
    ("1Cor", "7:17", "ἐκκλησία"): ("local", "", "no", ""),
    ("1Cor", "10:32", "ἐκκλησία"): ("universal", "", "sí", "judíos, griegos y la iglesia de Dios"),
    ("1Cor", "11:16", "ἐκκλησία"): ("local", "", "no", "αἱ ἐκκλησίαι τοῦ θεοῦ"),
    ("1Cor", "11:18", "ἐκκλησία"): ("reunion", "", "no", "συνερχομένων ὑμῶν ἐν ἐκκλησίᾳ"),
    ("1Cor", "11:22", "ἐκκλησία"): ("local", "", "no", ""),
    ("1Cor", "11:34", "οἶκος"): (NI, "", "no", "comer en casa"),
    ("1Cor", "12:5", "διάκονος"): ("funcion", "", "no", "διαιρέσεις διακονιῶν"),
    ("1Cor", "12:28", "ἐκκλησία"): ("universal", "", "sí", "ἔθετο ὁ θεὸς ἐν τῇ ἐκκλησίᾳ πρῶτον ἀποστόλους…: orden de funciones (apóstoles, profetas, maestros), sin cargos del léxico"),
    ("1Cor", "14:4", "ἐκκλησία"): ("reunion", "", "no", ""),
    ("1Cor", "14:5", "ἐκκλησία"): ("reunion", "", "no", ""),
    ("1Cor", "14:12", "ἐκκλησία"): ("reunion", "", "no", ""),
    ("1Cor", "14:19", "ἐκκλησία"): ("reunion", "", "no", ""),
    ("1Cor", "14:23", "ἐκκλησία"): ("reunion", "", "no", "συνέλθῃ ἡ ἐκκλησία ὅλη ἐπὶ τὸ αὐτό"),
    ("1Cor", "14:28", "ἐκκλησία"): ("reunion", "", "no", ""),
    ("1Cor", "14:33", "ἐκκλησία"): ("local", "", "no", ""),
    ("1Cor", "14:34", "ἐκκλησία"): ("reunion", "", "no", ""),
    ("1Cor", "14:35", "οἶκος"): (NI, "", "no", "preguntar en casa"),
    ("1Cor", "14:35", "ἐκκλησία"): ("reunion", "", "no", ""),
    ("1Cor", "15:9", "ἐκκλησία"): ("universal", "", "sí", "ἐδίωξα τὴν ἐκκλησίαν τοῦ θεοῦ"),
    ("1Cor", "16:1", "ἐκκλησία"): ("local", "", "no", "las iglesias de Galacia"),
    ("1Cor", "16:15", "διάκονος"): ("funcion", "", "no", "la casa de Estéfanas εἰς διακονίαν τοῖς ἁγίοις ἔταξαν ἑαυτούς"),
    ("1Cor", "16:19", "ἐκκλησία", "ἐκκλησίαι"): ("local", "", "no", "las iglesias de Asia"),
    ("1Cor", "16:19", "οἶκος"): ("celula", "", "no", "ἡ κατ’ οἶκον αὐτῶν ἐκκλησία"),
    ("1Cor", "16:19", "ἐκκλησία", "ἐκκλησίᾳ"): ("local", "", "no", "iglesia doméstica"),
    # ===== 2 Corintios =====
    ("2Cor", "1:1", "ἐκκλησία"): ("local", "", "no", "prescripto"),
    ("2Cor", "3:3", "διάκονος"): ("funcion", "", "no", "carta «servida» por Pablo"),
    ("2Cor", "3:6", "διάκονος"): ("funcion", "", "no", "διάκονοι καινῆς διαθήκης"),
    ("2Cor", "3:7", "διάκονος"): (NI, "", "no", "διακονία τοῦ θανάτου (Moisés)"),
    ("2Cor", "3:8", "διάκονος"): ("funcion", "", "no", "διακονία τοῦ πνεύματος"),
    ("2Cor", "3:9", "διάκονος"): (NI, "", "no", "antítesis condena / justicia"),
    ("2Cor", "4:1", "διάκονος"): ("funcion", "", "no", "ministerio apostólico"),
    ("2Cor", "5:18", "διάκονος"): ("funcion", "", "no", "διακονία τῆς καταλλαγῆς"),
    ("2Cor", "6:3", "διάκονος"): ("funcion", "", "no", ""),
    ("2Cor", "6:4", "διάκονος"): ("funcion", "", "no", "θεοῦ διάκονοι"),
    ("2Cor", "8:1", "ἐκκλησία"): ("local", "", "no", "las iglesias de Macedonia"),
    ("2Cor", "8:4", "διάκονος"): ("funcion", "", "no", "la colecta"),
    ("2Cor", "8:19", "χειροτονία"): ("funcion", "eleccion", "sí", "χειροτονηθεὶς ὑπὸ τῶν ἐκκλησιῶν συνέκδημος: elección de un delegado por las iglesias; no es rito de institución"),
    ("2Cor", "8:19", "διάκονος"): ("funcion", "", "no", "la colecta"),
    ("2Cor", "8:20", "διάκονος"): ("funcion", "", "no", "la colecta"),
    ("2Cor", "9:1", "διάκονος"): ("funcion", "", "no", "la colecta"),
    ("2Cor", "9:12", "διάκονος"): ("funcion", "", "no", "la colecta"),
    ("2Cor", "9:13", "διάκονος"): ("funcion", "", "no", "la colecta"),
    ("2Cor", "11:8", "ἐκκλησία"): ("local", "", "no", ""),
    ("2Cor", "11:8", "διάκονος"): ("funcion", "", "no", "servicio apostólico a Corinto"),
    ("2Cor", "11:15", "διάκονος"): (NI, "", "no", "los διάκονοι de Satanás / de la justicia"),
    ("2Cor", "11:23", "διάκονος"): ("funcion", "", "no", "διάκονοι Χριστοῦ (los adversarios y Pablo)"),
    ("2Cor", "12:13", "ἐκκλησία"): ("local", "", "no", ""),
    # ===== Gálatas =====
    ("Gal", "1:2", "ἐκκλησία"): ("local", "", "no", "prescripto"),
    ("Gal", "1:13", "ἐκκλησία"): ("universal", "", "sí", "ἐδίωκον τὴν ἐκκλησίαν τοῦ θεοῦ"),
    ("Gal", "1:22", "ἐκκλησία"): ("local", "", "no", "las iglesias de Judea"),
    ("Gal", "2:17", "διάκονος"): (NI, "", "no", "Cristo ἁμαρτίας διάκονος (μὴ γένοιτο)"),
    # ===== Filipenses =====
    ("Flp", "1:1", "ἐπίσκοπος"): ("cargo", "colegio", "no", "σὺν ἐπισκόποις καὶ διακόνοις: plural, sin requisitos ni jerarquía"),
    ("Flp", "1:1", "διάκονος"): ("cargo", "colegio", "no", "σὺν ἐπισκόποις καὶ διακόνοις"),
    ("Flp", "2:3", "ἡγούμενος"): (NI, "", "no", "ἡγέομαι «considerar»"),
    ("Flp", "3:6", "ἐκκλησία"): ("universal", "", "sí", "διώκων τὴν ἐκκλησίαν"),
    ("Flp", "4:15", "ἐκκλησία"): ("local", "", "no", ""),
    # ===== 1 Tesalonicenses =====
    ("1Tes", "1:1", "ἐκκλησία"): ("local", "", "no", "prescripto"),
    ("1Tes", "5:12", "προϊστάμενος"): ("funcion", "", "no", "τοὺς κοπιῶντας … καὶ προϊσταμένους ὑμῶν ἐν κυρίῳ καὶ νουθετοῦντας: función sin título"),
    # ===== Filemón =====
    ("Flm", "1:2", "οἶκος"): ("celula", "", "no", "ἡ κατ’ οἶκόν σου ἐκκλησία"),
    ("Flm", "1:2", "ἐκκλησία"): ("local", "", "no", "iglesia doméstica"),
    ("Flm", "1:13", "διάκονος"): (NI, "", "no", "Onésimo sirviendo a Pablo"),
    # ===== Efesios =====
    ("Ef", "1:22", "ἐκκλησία"): ("universal", "", "no", "cuerpo de Cristo"),
    ("Ef", "3:7", "διάκονος"): ("funcion", "", "no", "Pablo διάκονος del evangelio"),
    ("Ef", "3:10", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Ef", "3:21", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Ef", "4:12", "διάκονος"): ("funcion", "", "no", "ἔργον διακονίας de los santos"),
    ("Ef", "5:23", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Ef", "5:24", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Ef", "5:25", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Ef", "5:27", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Ef", "5:29", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Ef", "5:32", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Ef", "6:21", "διάκονος"): ("funcion", "", "no", "Tíquico, πιστὸς διάκονος ἐν κυρίῳ: colaborador, sin cargo local"),
    # ===== Colosenses =====
    ("Col", "1:7", "διάκονος"): ("funcion", "", "no", "Epafras, πιστὸς διάκονος τοῦ Χριστοῦ"),
    ("Col", "1:18", "ἐκκλησία"): ("universal", "", "no", "cuerpo de Cristo"),
    ("Col", "1:23", "διάκονος"): ("funcion", "", "no", "Pablo διάκονος del evangelio"),
    ("Col", "1:24", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Col", "1:25", "διάκονος"): ("funcion", "", "no", ""),
    ("Col", "4:7", "διάκονος"): ("funcion", "", "no", "Tíquico"),
    ("Col", "4:15", "οἶκος"): ("celula", "", "no", "ἡ κατ’ οἶκον αὐτῆς ἐκκλησία (Ninfa)"),
    ("Col", "4:15", "ἐκκλησία"): ("local", "", "no", "iglesia doméstica"),
    ("Col", "4:16", "ἐκκλησία"): ("local", "", "no", "la iglesia de Laodicea"),
    ("Col", "4:17", "διάκονος"): ("funcion", "", "sí", "Arquipo: τὴν διακονίαν ἣν παρέλαβες ἐν κυρίῳ: ministerio recibido, sin título"),
    # ===== 2 Tesalonicenses =====
    ("2Tes", "1:1", "ἐκκλησία"): ("local", "", "no", "prescripto"),
    ("2Tes", "1:4", "ἐκκλησία"): ("local", "", "no", "αἱ ἐκκλησίαι τοῦ θεοῦ"),
    # ===== 1 Timoteo =====
    ("1Tim", "1:12", "διάκονος"): ("funcion", "", "no", "Pablo θέμενος εἰς διακονίαν"),
    ("1Tim", "3:1", "ἐπίσκοπος"): ("cargo", "requisitos", "no", "ἐπισκοπή como cargo al que se aspira (καλοῦ ἔργου ἐπιθυμεῖ)"),
    ("1Tim", "3:2", "ἐπίσκοπος"): ("cargo", "requisitos", "sí", "δεῖ τὸν ἐπίσκοπον ἀνεπίλημπτον εἶναι, μιᾶς γυναικὸς ἄνδρα…: lista de requisitos; singular genérico frente a διάκονοι plural (3,8): no se codifica monoepiscopado porque el singular es distributivo («quien aspire»), juicio"),
    ("1Tim", "3:4", "προϊστάμενος"): (NI, "", "no", "gobierno de la propia casa como requisito del ἐπίσκοπος (el rasgo va en la fila de ἐπίσκοπος)"),
    ("1Tim", "3:4", "οἶκος"): ("celula", "", "sí", "τοῦ ἰδίου οἴκου καλῶς προϊστάμενον: la casa como unidad de gobierno análoga a la iglesia (3,5)"),
    ("1Tim", "3:5", "προϊστάμενος"): (NI, "", "no", "ídem"),
    ("1Tim", "3:5", "οἶκος"): ("celula", "", "sí", "εἰ δέ τις τοῦ ἰδίου οἴκου προστῆναι οὐκ οἶδεν, πῶς ἐκκλησίας θεοῦ ἐπιμελήσεται"),
    ("1Tim", "3:5", "ἐκκλησία"): ("local", "", "no", "ἐκκλησίας θεοῦ ἐπιμελήσεται: la comunidad gobernada"),
    ("1Tim", "3:8", "διάκονος"): ("cargo", "requisitos;colegio", "no", "διακόνους ὡσαύτως σεμνούς…: lista de requisitos, plural"),
    ("1Tim", "3:10", "διάκονος"): ("cargo", "requisitos;eleccion", "sí", "δοκιμαζέσθωσαν πρῶτον, εἶτα διακονείτωσαν: prueba previa (juicio: elección o examen)"),
    ("1Tim", "3:12", "διάκονος"): ("cargo", "requisitos;colegio", "no", "διάκονοι ἔστωσαν μιᾶς γυναικὸς ἄνδρες"),
    ("1Tim", "3:12", "προϊστάμενος"): (NI, "", "no", "gobierno de la casa como requisito del διάκονος"),
    ("1Tim", "3:12", "οἶκος"): ("celula", "", "sí", "τέκνων καλῶς προϊστάμενοι καὶ τῶν ἰδίων οἴκων"),
    ("1Tim", "3:13", "διάκονος"): ("cargo", "", "sí", "οἱ καλῶς διακονήσαντες βαθμὸν ἑαυτοῖς καλὸν περιποιοῦνται: el servicio como grado (juicio: ¿carrera de cargos?)"),
    ("1Tim", "3:15", "οἶκος"): (NI, "", "sí", "ἐν οἴκῳ θεοῦ … ἥτις ἐστὶν ἐκκλησία θεοῦ ζῶντος: metáfora de la iglesia como casa de Dios, no célula"),
    ("1Tim", "3:15", "ἐκκλησία"): ("universal", "", "sí", "ἐκκλησία θεοῦ ζῶντος, στῦλος καὶ ἑδραίωμα τῆς ἀληθείας"),
    ("1Tim", "4:6", "διάκονος"): ("funcion", "", "no", "Timoteo καλὸς διάκονος Χριστοῦ Ἰησοῦ"),
    ("1Tim", "4:14", "ἐπίθεσις χειρῶν"): ("rito", "", "no", "carisma dado διὰ προφητείας μετὰ ἐπιθέσεως τῶν χειρῶν τοῦ πρεσβυτερίου: rito de institución"),
    ("1Tim", "4:14", "πρεσβύτερος"): ("cargo", "colegio", "no", "τὸ πρεσβυτέριον que impone las manos"),
    ("1Tim", "5:1", "πρεσβύτερος"): (NI, "", "no", "anciano de edad (πρεσβυτέρῳ … ὡς πατέρα)"),
    ("1Tim", "5:1", "νεώτερος"): (NI, "", "no", "jóvenes de edad (ὡς ἀδελφούς)"),
    ("1Tim", "5:2", "πρεσβύτερος"): (NI, "", "no", "ancianas de edad (ὡς μητέρας)"),
    ("1Tim", "5:2", "νεώτερος"): (NI, "", "no", "jóvenes de edad (ὡς ἀδελφάς)"),
    ("1Tim", "5:3", "χήρα"): ("categoria", "", "no", "χήρας τίμα τὰς ὄντως χήρας: categoría reconocida («verdaderas viudas»)"),
    ("1Tim", "5:4", "χήρα"): ("categoria", "", "no", ""),
    ("1Tim", "5:4", "οἶκος"): (NI, "", "no", "τὸν ἴδιον οἶκον εὐσεβεῖν: la familia"),
    ("1Tim", "5:5", "χήρα"): ("categoria", "requisitos", "no", "ἡ ὄντως χήρα καὶ μεμονωμένη … προσμένει ταῖς δεήσεσιν"),
    ("1Tim", "5:9", "χήρα"): ("categoria", "registro;requisitos", "no", "χήρα καταλεγέσθω μὴ ἔλαττον ἐτῶν ἑξήκοντα γεγονυῖα, ἑνὸς ἀνδρὸς γυνή: lista con requisitos de edad y conducta"),
    ("1Tim", "5:11", "νεώτερος"): ("categoria", "", "sí", "νεωτέρας δὲ χήρας παραιτοῦ: subgrupo de las viudas por edad"),
    ("1Tim", "5:11", "χήρα"): ("categoria", "requisitos", "no", "exclusión de las viudas jóvenes de la lista"),
    ("1Tim", "5:14", "νεώτερος"): ("categoria", "", "sí", "βούλομαι οὖν νεωτέρας γαμεῖν: las viudas jóvenes"),
    ("1Tim", "5:16", "χήρα"): ("categoria", "", "no", "ἵνα ταῖς ὄντως χήραις ἐπαρκέσῃ: la iglesia sostiene a las viudas de la lista"),
    ("1Tim", "5:16", "ἐκκλησία"): ("local", "", "no", "μὴ βαρείσθω ἡ ἐκκλησία: la comunidad como caja"),
    ("1Tim", "5:17", "προϊστάμενος"): ("cargo", "", "no", "οἱ καλῶς προεστῶτες πρεσβύτεροι: presbíteros que presiden"),
    ("1Tim", "5:17", "πρεσβύτερος"): ("cargo", "remuneracion;colegio", "no", "διπλῆς τιμῆς ἀξιούσθωσαν, μάλιστα οἱ κοπιῶντες ἐν λόγῳ καὶ διδασκαλίᾳ; 5,18 ἄξιος ὁ ἐργάτης τοῦ μισθοῦ αὐτοῦ"),
    ("1Tim", "5:19", "πρεσβύτερος"): ("cargo", "disciplina", "no", "κατὰ πρεσβυτέρου κατηγορίαν μὴ παραδέχου ἐκτὸς εἰ μὴ ἐπὶ δύο ἢ τριῶν μαρτύρων; 5,20 τοὺς ἁμαρτάνοντας ἐνώπιον πάντων ἔλεγχε"),
    ("1Tim", "5:22", "ἐπίθεσις χειρῶν"): ("rito", "", "sí", "χεῖρας ταχέως μηδενὶ ἐπιτίθει: rito de institución (o de reconciliación: juicio)"),
    # ===== 2 Timoteo =====
    ("2Tim", "1:6", "ἐπίθεσις χειρῶν"): ("rito", "", "no", "τὸ χάρισμα … διὰ τῆς ἐπιθέσεως τῶν χειρῶν μου: rito de institución por Pablo"),
    ("2Tim", "1:16", "οἶκος"): ("celula", "", "sí", "τῷ Ὀνησιφόρου οἴκῳ: la casa como unidad de saludo/bendición"),
    ("2Tim", "4:5", "διάκονος"): ("funcion", "", "no", "τὴν διακονίαν σου πληροφόρησον (Timoteo)"),
    ("2Tim", "4:11", "διάκονος"): (NI, "", "sí", "Marcos εὔχρηστος εἰς διακονίαν: servicio personal a Pablo (juicio)"),
    ("2Tim", "4:19", "οἶκος"): ("celula", "", "sí", "τὸν Ὀνησιφόρου οἶκον: saludo a la casa"),
    # ===== Tito =====
    ("Tit", "1:5", "πρεσβύτερος"): ("cargo", "eleccion;requisitos;colegio", "no", "καταστήσῃς κατὰ πόλιν πρεσβυτέρους … εἴ τίς ἐστιν ἀνέγκλητος: institución por el delegado, con requisitos, un colegio por ciudad"),
    ("Tit", "1:7", "ἐπίσκοπος"): ("cargo", "requisitos", "sí", "δεῖ γὰρ τὸν ἐπίσκοπον ἀνέγκλητον εἶναι ὡς θεοῦ οἰκονόμον: singular genérico que continúa a los πρεσβύτεροι de 1,5 (juicio: identidad de ambos títulos); sin monoepiscopado"),
    ("Tit", "1:11", "οἶκος"): ("celula", "", "sí", "ὅλους οἴκους ἀνατρέπουσιν: casas enteras como unidades de la comunidad"),
    ("Tit", "2:6", "νεώτερος"): ("categoria", "", "sí", "τοὺς νεωτέρους ὡσαύτως παρακάλει σωφρονεῖν: grupo del código doméstico (2,2-6: ancianos, ancianas, jóvenes casadas, jóvenes)"),
    ("Tit", "3:8", "προϊστάμενος"): (NI, "", "no", "καλῶν ἔργων προΐστασθαι"),
    ("Tit", "3:14", "προϊστάμενος"): (NI, "", "no", "καλῶν ἔργων προΐστασθαι"),
    # ===== Hebreos =====
    ("Heb", "1:14", "διάκονος"): (NI, "", "no", "los ángeles εἰς διακονίαν ἀποστελλόμενα"),
    ("Heb", "2:12", "ἐκκλησία"): (NI, "", "no", "cita de Sal 22,23 LXX (ἐν μέσῳ ἐκκλησίας)"),
    ("Heb", "3:2", "οἶκος"): (NI, "", "no", "Nm 12,7: la casa de Dios (Moisés)"),
    ("Heb", "3:3", "οἶκος"): (NI, "", "no", "casa construida"),
    ("Heb", "3:4", "οἶκος"): (NI, "", "no", ""),
    ("Heb", "3:5", "οἶκος"): (NI, "", "no", "Nm 12,7"),
    ("Heb", "3:6", "οἶκος"): (NI, "", "sí", "οὗ οἶκός ἐσμεν ἡμεῖς: metáfora de la comunidad como casa de Dios, no célula"),
    ("Heb", "6:2", "ἐπίθεσις χειρῶν"): ("rito", "", "sí", "βαπτισμῶν διδαχῆς ἐπιθέσεώς τε χειρῶν: rito de la catequesis elemental, junto al bautismo (no de institución: juicio)"),
    ("Heb", "6:10", "διάκονος"): ("funcion", "", "no", "διακονήσαντες τοῖς ἁγίοις καὶ διακονοῦντες: servicio a los santos"),
    ("Heb", "8:8", "οἶκος"): (NI, "", "no", "Jr 31,31: casa de Israel / de Judá"),
    ("Heb", "8:10", "οἶκος"): (NI, "", "no", "Jr 31,33"),
    ("Heb", "10:21", "οἶκος"): (NI, "", "sí", "ἱερέα μέγαν ἐπὶ τὸν οἶκον τοῦ θεοῦ: metáfora"),
    ("Heb", "11:2", "πρεσβύτερος"): (NI, "", "no", "οἱ πρεσβύτεροι = los antiguos (los padres de la fe)"),
    ("Heb", "11:7", "οἶκος"): (NI, "", "no", "la casa de Noé"),
    ("Heb", "12:15", "ἐπίσκοπος"): (NI, "", "no", "ἐπισκοποῦντες μή τις ὑστερῶν: «velar» sin cargo (exhortación a todos)"),
    ("Heb", "12:19", "προϊστάμενος"): (NI, "", "no", "προστεθῆναι (προστίθημι), falso positivo"),
    ("Heb", "12:23", "ἐκκλησία"): (NI, "", "sí", "ἐκκλησίᾳ πρωτοτόκων ἀπογεγραμμένων ἐν οὐρανοῖς: asamblea celestial"),
    ("Heb", "13:7", "ἡγούμενος"): ("funcion", "", "sí", "μνημονεύετε τῶν ἡγουμένων ὑμῶν οἵτινες ἐλάλησαν ὑμῖν τὸν λόγον τοῦ θεοῦ: dirigentes difuntos, sin título fijo ni requisitos (juicio: cargo o función)"),
    ("Heb", "13:17", "ἡγούμενος"): ("funcion", "", "sí", "πείθεσθε τοῖς ἡγουμένοις ὑμῶν καὶ ὑπείκετε· αὐτοὶ γὰρ ἀγρυπνοῦσιν ὑπὲρ τῶν ψυχῶν ὑμῶν ὡς λόγον ἀποδώσοντες: dirigentes con responsabilidad, sin título fijo (juicio)"),
    ("Heb", "13:24", "ἡγούμενος"): ("funcion", "", "sí", "ἀσπάσασθε πάντας τοὺς ἡγουμένους ὑμῶν καὶ πάντας τοὺς ἁγίους"),
    # ===== Hechos =====
    ("Hch", "1:17", "διάκονος"): ("funcion", "", "no", "ὁ κλῆρος τῆς διακονίας ταύτης (apostolado)"),
    ("Hch", "1:20", "ἐπίσκοπος"): ("funcion", "", "sí", "τὴν ἐπισκοπὴν αὐτοῦ λαβέτω ἕτερος (Sal 109,8 LXX) aplicado al puesto de Judas"),
    ("Hch", "1:25", "διάκονος"): ("funcion", "", "no", "τὸν τόπον τῆς διακονίας ταύτης καὶ ἀποστολῆς"),
    ("Hch", "2:17", "πρεσβύτερος"): (NI, "", "no", "Jl 3,1 LXX: los ancianos de edad"),
    ("Hch", "4:5", "πρεσβύτερος"): (NI, "", "no", "institución judía (sanedrín)"),
    ("Hch", "4:8", "πρεσβύτερος"): (NI, "", "no", "institución judía"),
    ("Hch", "4:23", "πρεσβύτερος"): (NI, "", "no", "institución judía"),
    ("Hch", "5:6", "νεώτερος"): ("categoria", "", "sí", "ἀναστάντες δὲ οἱ νεώτεροι συνέστειλαν αὐτόν: los jóvenes actúan como grupo (juicio: edad o categoría)"),
    ("Hch", "6:1", "διάκονος"): ("funcion", "", "no", "ἡ διακονία ἡ καθημερινή: el servicio diario a las viudas"),
    ("Hch", "6:1", "χήρα"): ("categoria", "", "sí", "αἱ χῆραι αὐτῶν παρεθεωροῦντο ἐν τῇ διακονίᾳ: las viudas como grupo atendido (juicio)"),
    ("Hch", "6:2", "διάκονος"): ("funcion", "", "no", "διακονεῖν τραπέζαις"),
    ("Hch", "6:4", "διάκονος"): ("funcion", "", "no", "ἡ διακονία τοῦ λόγου (los Doce)"),
    ("Hch", "6:6", "ἐπίθεσις χειρῶν"): ("rito", "eleccion", "no", "los Siete: ἐπισκέψασθε … ἄνδρας ἐξ ὑμῶν μαρτυρουμένους ἑπτά (6,3, elección con requisitos) … προσευξάμενοι ἐπέθηκαν αὐτοῖς τὰς χεῖρας: rito de institución"),
    ("Hch", "6:12", "πρεσβύτερος"): (NI, "", "no", "institución judía"),
    ("Hch", "7:10", "ἡγούμενος"): (NI, "", "no", "José ἡγούμενος de Egipto"),
    ("Hch", "8:17", "ἐπίθεσις χειρῶν"): ("rito", "", "sí", "ἐπετίθεσαν τὰς χεῖρας ἐπ’ αὐτοὺς καὶ ἐλάμβανον πνεῦμα ἅγιον: rito posbautismal, no de institución (juicio)"),
    ("Hch", "8:18", "ἐπίθεσις χειρῶν"): ("rito", "", "sí", "διὰ τῆς ἐπιθέσεως τῶν χειρῶν τῶν ἀποστόλων δίδοται τὸ πνεῦμα"),
    ("Hch", "8:19", "ἐπίθεσις χειρῶν"): ("rito", "", "sí", "Simón pide el poder de imponer las manos"),
    ("Hch", "9:12", "ἐπίθεσις χειρῶν"): (NI, "", "no", "curación de Saulo (visión)"),
    ("Hch", "9:17", "ἐπίθεσις χειρῶν"): (NI, "", "no", "curación de Saulo"),
    ("Hch", "9:39", "χήρα"): ("categoria", "", "sí", "πᾶσαι αἱ χῆραι κλαίουσαι (Jope): las viudas como grupo de la comunidad (juicio)"),
    ("Hch", "9:41", "χήρα"): ("categoria", "", "sí", "φωνήσας τοὺς ἁγίους καὶ τὰς χήρας: junto a «los santos», como grupo"),
    ("Hch", "10:33", "προϊστάμενος"): (NI, "", "no", "προστάσσω, falso positivo"),
    ("Hch", "11:29", "διάκονος"): ("funcion", "", "no", "colecta de Antioquía"),
    ("Hch", "11:30", "πρεσβύτερος"): ("cargo", "colegio", "no", "ἀποστείλαντες πρὸς τοὺς πρεσβυτέρους (Jerusalén): reciben la colecta"),
    ("Hch", "12:25", "διάκονος"): ("funcion", "", "no", "colecta"),
    ("Hch", "13:3", "ἐπίθεσις χειρῶν"): ("rito", "", "no", "νηστεύσαντες καὶ προσευξάμενοι καὶ ἐπιθέντες τὰς χεῖρας αὐτοῖς ἀπέλυσαν: envío de Bernabé y Saulo"),
    ("Hch", "14:12", "ἡγούμενος"): (NI, "", "no", "ὁ ἡγούμενος τοῦ λόγου (Pablo como orador principal)"),
    ("Hch", "14:23", "χειροτονία"): ("rito", "eleccion", "sí", "χειροτονήσαντες δὲ αὐτοῖς κατ’ ἐκκλησίαν πρεσβυτέρους, προσευξάμενοι μετὰ νηστειῶν: institución de presbíteros por Pablo y Bernabé, con oración y ayuno (juicio: elección o nombramiento)"),
    ("Hch", "14:23", "πρεσβύτερος"): ("cargo", "eleccion;colegio", "no", "presbíteros por iglesia"),
    ("Hch", "15:2", "πρεσβύτερος"): ("cargo", "colegio", "no", "οἱ ἀπόστολοι καὶ πρεσβύτεροι (Jerusalén)"),
    ("Hch", "15:4", "πρεσβύτερος"): ("cargo", "colegio", "no", ""),
    ("Hch", "15:6", "πρεσβύτερος"): ("cargo", "colegio", "no", ""),
    ("Hch", "15:22", "πρεσβύτερος"): ("cargo", "colegio", "no", ""),
    ("Hch", "15:22", "ἡγούμενος"): ("funcion", "", "sí", "ἄνδρας ἡγουμένους ἐν τοῖς ἀδελφοῖς: Judas y Silas, «dirigentes entre los hermanos», sin título (juicio)"),
    ("Hch", "15:23", "πρεσβύτερος"): ("cargo", "colegio", "no", ""),
    ("Hch", "16:4", "πρεσβύτερος"): ("cargo", "colegio", "no", "τὰ δόγματα τὰ κεκριμένα ὑπὸ τῶν ἀποστόλων καὶ πρεσβυτέρων"),
    ("Hch", "17:26", "προϊστάμενος"): (NI, "", "no", "προστάσσω, falso positivo"),
    ("Hch", "19:22", "διάκονος"): ("funcion", "", "sí", "δύο τῶν διακονούντων αὐτῷ (Timoteo y Erasto): colaboradores de Pablo (juicio)"),
    ("Hch", "20:17", "πρεσβύτερος"): ("cargo", "colegio", "no", "τοὺς πρεσβυτέρους τῆς ἐκκλησίας (Éfeso)"),
    ("Hch", "20:24", "διάκονος"): ("funcion", "", "no", "τὴν διακονίαν ἣν ἔλαβον παρὰ τοῦ κυρίου (Pablo)"),
    ("Hch", "20:28", "ἐπίσκοπος"): ("cargo", "colegio", "sí", "ὑμᾶς τὸ πνεῦμα τὸ ἅγιον ἔθετο ἐπισκόπους ποιμαίνειν τὴν ἐκκλησίαν τοῦ θεοῦ: los presbíteros de Éfeso (20,17) llamados ἐπίσκοποι (juicio: identidad de ambos títulos)"),
    ("Hch", "21:18", "πρεσβύτερος"): ("cargo", "colegio", "no", "Santiago y todos los presbíteros"),
    ("Hch", "21:19", "διάκονος"): ("funcion", "", "no", "ministerio de Pablo entre los gentiles"),
    ("Hch", "22:5", "πρεσβύτερος"): (NI, "", "no", "πᾶν τὸ πρεσβυτέριον: institución judía"),
    ("Hch", "23:14", "πρεσβύτερος"): (NI, "", "no", "institución judía"),
    ("Hch", "24:1", "πρεσβύτερος"): (NI, "", "no", "institución judía"),
    ("Hch", "25:15", "πρεσβύτερος"): (NI, "", "no", "institución judía"),
    ("Hch", "19:6", "ἐπίθεσις χειρῶν"): ("rito", "", "sí", "ἐπιθέντος αὐτοῖς τοῦ Παύλου χεῖρας ἦλθεν τὸ πνεῦμα: rito posbautismal (juicio)"),
    ("Hch", "28:8", "ἐπίθεσις χειρῶν"): (NI, "", "no", "curación del padre de Publio"),
    ("Hch", "2:2", "οἶκος"): (NI, "", "no", "la casa de Pentecostés"),
    ("Hch", "2:36", "οἶκος"): (NI, "", "no", "casa de Israel"),
    ("Hch", "2:46", "οἶκος"): ("celula", "", "no", "κλῶντές τε κατ’ οἶκον ἄρτον: la casa como lugar de la fracción del pan"),
    ("Hch", "5:11", "ἐκκλησία"): ("local", "", "no", "ὅλην τὴν ἐκκλησίαν (Jerusalén)"),
    ("Hch", "5:42", "οἶκος"): ("celula", "", "no", "ἐν τῷ ἱερῷ καὶ κατ’ οἶκον … διδάσκοντες"),
    ("Hch", "7:10", "οἶκος"): (NI, "", "no", "casa del faraón"),
    ("Hch", "7:20", "οἶκος"): (NI, "", "no", ""),
    ("Hch", "7:38", "ἐκκλησία"): (NI, "", "no", "ἡ ἐκκλησία ἐν τῇ ἐρήμῳ (Israel)"),
    ("Hch", "7:42", "οἶκος"): (NI, "", "no", "Am 5,25"),
    ("Hch", "7:47", "οἶκος"): (NI, "", "no", "el templo de Salomón"),
    ("Hch", "7:49", "οἶκος"): (NI, "", "no", "Is 66,1"),
    ("Hch", "8:1", "ἐκκλησία"): ("local", "", "no", "la iglesia de Jerusalén"),
    ("Hch", "8:3", "ἐκκλησία"): ("local", "", "no", ""),
    ("Hch", "8:3", "οἶκος"): ("celula", "", "sí", "κατὰ τοὺς οἴκους εἰσπορευόμενος: Saulo persigue casa por casa (juicio: las casas como células)"),
    ("Hch", "9:31", "ἐκκλησία"): ("local", "", "sí", "ἡ ἐκκλησία καθ’ ὅλης τῆς Ἰουδαίας καὶ Γαλιλαίας καὶ Σαμαρείας: singular regional (juicio)"),
    ("Hch", "10:2", "οἶκος"): ("celula", "", "sí", "Cornelio σὺν παντὶ τῷ οἴκῳ αὐτοῦ: la casa como unidad de conversión (10,44-48)"),
    ("Hch", "10:22", "οἶκος"): (NI, "", "no", "la casa de Cornelio (edificio)"),
    ("Hch", "10:30", "οἶκος"): (NI, "", "no", ""),
    ("Hch", "11:12", "οἶκος"): (NI, "", "no", ""),
    ("Hch", "11:13", "οἶκος"): (NI, "", "no", ""),
    ("Hch", "11:14", "οἶκος"): ("celula", "", "no", "σωθήσῃ σὺ καὶ πᾶς ὁ οἶκός σου: la casa como unidad de salvación/bautismo"),
    ("Hch", "11:22", "ἐκκλησία"): ("local", "", "no", ""),
    ("Hch", "11:26", "ἐκκλησία"): ("local", "", "no", "Antioquía"),
    ("Hch", "12:1", "ἐκκλησία"): ("local", "", "no", ""),
    ("Hch", "12:5", "ἐκκλησία"): ("local", "", "no", ""),
    ("Hch", "13:1", "ἐκκλησία"): ("local", "", "no", "Antioquía: profetas y maestros"),
    ("Hch", "14:23", "ἐκκλησία"): ("local", "", "no", "κατ’ ἐκκλησίαν πρεσβυτέρους"),
    ("Hch", "14:27", "ἐκκλησία"): ("reunion", "", "no", "συναγαγόντες τὴν ἐκκλησίαν"),
    ("Hch", "15:3", "ἐκκλησία"): ("local", "", "no", ""),
    ("Hch", "15:4", "ἐκκλησία"): ("local", "", "no", ""),
    ("Hch", "15:22", "ἐκκλησία"): ("reunion", "", "no", "σὺν ὅλῃ τῇ ἐκκλησίᾳ ἐκλεξαμένους: la asamblea elige delegados"),
    ("Hch", "15:41", "ἐκκλησία"): ("local", "", "no", ""),
    ("Hch", "16:5", "ἐκκλησία"): ("local", "", "no", ""),
    ("Hch", "16:15", "οἶκος", "οἶκοσ"): ("celula", "", "no", "ἐβαπτίσθη καὶ ὁ οἶκος αὐτῆς (Lidia)"),
    ("Hch", "16:15", "οἶκος", "οἶκον"): (NI, "", "no", "la casa de Lidia como alojamiento"),
    ("Hch", "16:31", "οἶκος"): ("celula", "", "no", "σωθήσῃ σὺ καὶ ὁ οἶκός σου (carcelero)"),
    ("Hch", "16:34", "οἶκος"): (NI, "", "no", "la casa del carcelero (edificio)"),
    ("Hch", "18:8", "οἶκος"): ("celula", "", "no", "Crispo ἐπίστευσεν σὺν ὅλῳ τῷ οἴκῳ αὐτοῦ"),
    ("Hch", "18:22", "ἐκκλησία"): ("local", "", "no", ""),
    ("Hch", "19:16", "οἶκος"): (NI, "", "no", ""),
    ("Hch", "19:32", "ἐκκλησία"): (NI, "", "no", "asamblea cívica de Éfeso"),
    ("Hch", "19:39", "ἐκκλησία"): (NI, "", "no", "ἡ ἔννομος ἐκκλησία"),
    ("Hch", "19:40", "ἐκκλησία"): (NI, "", "no", "asamblea cívica"),
    ("Hch", "20:17", "ἐκκλησία"): ("local", "", "no", ""),
    ("Hch", "20:20", "οἶκος"): ("celula", "", "no", "δημοσίᾳ καὶ κατ’ οἴκους"),
    ("Hch", "20:28", "ἐκκλησία"): ("local", "", "no", ""),
    ("Hch", "21:8", "οἶκος"): (NI, "", "no", "la casa de Felipe (edificio)"),
    # ===== 1 Clemente =====
    ("1Clem", "0:1", "ἐκκλησία"): ("local", "", "no", "prescripto: ἡ ἐκκλησία τοῦ θεοῦ ἡ παροικοῦσα Ῥώμην τῇ … παροικούσῃ Κόρινθον"),
    ("1Clem", "1:3", "ἡγούμενος"): ("funcion", "", "sí", "ὑποτασσόμενοι τοῖς ἡγουμένοις ὑμῶν: dirigentes sin título fijo (juicio)"),
    ("1Clem", "1:3", "πρεσβύτερος"): ("cargo", "colegio", "sí", "τιμὴν τὴν καθήκουσαν ἀπονέμοντες τοῖς παρ’ ὑμῖν πρεσβυτέροις (juicio: cargo o edad; la carta trata de la deposición de presbíteros, 44,3-6)"),
    ("1Clem", "1:3", "οἶκος"): (NI, "", "no", "τὰ κατὰ τὸν οἶκον σεμνῶς οἰκουργεῖν"),
    ("1Clem", "2:8", "προϊστάμενος"): (NI, "", "no", "προστάγματα, falso positivo"),
    ("1Clem", "3:3", "πρεσβύτερος"): (NI, "", "no", "Is 3,5: οἱ νέοι ἐπὶ τοὺς πρεσβυτέρους (edad)"),
    ("1Clem", "3:4", "προϊστάμενος"): (NI, "", "no", "falso positivo"),
    ("1Clem", "5:7", "ἡγούμενος"): (NI, "", "no", "los gobernantes (Pablo martirizado ἐπὶ τῶν ἡγουμένων)"),
    ("1Clem", "8:2", "προϊστάμενος"): (NI, "", "no", "προστίθημι, falso positivo"),
    ("1Clem", "8:3", "οἶκος"): (NI, "", "no", "casa de Israel"),
    ("1Clem", "8:4", "χήρα"): (NI, "", "no", "Is 1,17"),
    ("1Clem", "10:2", "οἶκος"): (NI, "", "no", "Gn 12,1"),
    ("1Clem", "10:3", "οἶκος"): (NI, "", "no", ""),
    ("1Clem", "12:5", "οἶκος"): (NI, "", "no", "Rahab"),
    ("1Clem", "12:7", "οἶκος"): (NI, "", "no", ""),
    ("1Clem", "17:5", "οἶκος"): (NI, "", "no", "Nm 12,7"),
    ("1Clem", "43:1", "οἶκος"): (NI, "", "no", "Nm 12,7"),
    ("1Clem", "20:5", "προϊστάμενος"): (NI, "", "no", "falso positivo"),
    ("1Clem", "21:6", "πρεσβύτερος"): ("cargo", "", "sí", "τοὺς προηγουμένους ἡμῶν αἰδεσθῶμεν, τοὺς πρεσβυτέρους τιμήσωμεν, τοὺς νέους παιδεύσωμεν (juicio: cargo o edad)"),
    ("1Clem", "32:2", "ἡγούμενος"): (NI, "", "no", "reyes y gobernantes de Judá"),
    ("1Clem", "36:1", "προϊστάμενος"): (NI, "", "no", "Cristo προστάτης καὶ βοηθός (título cristológico)"),
    ("1Clem", "37:1", "προϊστάμενος"): (NI, "", "no", "falso positivo"),
    ("1Clem", "37:2", "ἡγούμενος"): (NI, "", "no", "jefes militares"),
    ("1Clem", "37:3", "ἡγούμενος"): (NI, "", "no", "jefes militares"),
    ("1Clem", "40:4", "προϊστάμενος"): (NI, "", "no", "falso positivo"),
    ("1Clem", "40:5", "προϊστάμενος"): (NI, "", "no", "falso positivo"),
    ("1Clem", "40:5", "διάκονος"): (NI, "", "sí", "λευίταις ἴδιαι διακονίαι: analogía levítica (juicio)"),
    ("1Clem", "42:4", "ἐπίσκοπος"): ("cargo", "eleccion;requisitos;colegio", "no", "καθίστανον τὰς ἀπαρχὰς αὐτῶν, δοκιμάσαντες τῷ πνεύματι, εἰς ἐπισκόπους καὶ διακόνους: institución por los apóstoles tras prueba"),
    ("1Clem", "42:4", "διάκονος"): ("cargo", "eleccion;requisitos;colegio", "no", ""),
    ("1Clem", "42:5", "ἐπίσκοπος"): ("cargo", "colegio", "no", "Is 60,17 reinterpretado"),
    ("1Clem", "42:5", "διάκονος"): ("cargo", "colegio", "no", ""),
    ("1Clem", "44:1", "ἐπίσκοπος"): ("cargo", "sucesion", "no", "ἔρις ἔσται ἐπὶ τοῦ ὀνόματος τῆς ἐπισκοπῆς; 44,2 ἐπινομὴν δεδώκασιν ὅπως … διαδέξωνται ἕτεροι δεδοκιμασμένοι ἄνδρες"),
    ("1Clem", "44:4", "ἐπίσκοπος"): ("cargo", "disciplina;sucesion", "no", "τοὺς ἀμέμπτως καὶ ὁσίως προσενεγκόντας τὰ δῶρα τῆς ἐπισκοπῆς ἀποβάλωμεν: deposición (disciplina) de quienes ofrecen los dones"),
    ("1Clem", "44:5", "πρεσβύτερος"): ("cargo", "colegio", "no", "οἱ προοδοιπορήσαντες πρεσβύτεροι"),
    ("1Clem", "44:3", "ἐκκλησία"): ("reunion", "", "no", "συνευδοκησάσης τῆς ἐκκλησίας πάσης: la comunidad consiente la institución"),
    ("1Clem", "47:6", "πρεσβύτερος"): ("cargo", "colegio", "no", "στασιάζειν πρὸς τοὺς πρεσβυτέρους"),
    ("1Clem", "47:6", "ἐκκλησία"): ("local", "", "no", "la iglesia de Corinto"),
    ("1Clem", "50:3", "ἐπίσκοπος"): (NI, "", "no", "ἐν τῇ ἐπισκοπῇ τῆς βασιλείας: visita de Dios"),
    ("1Clem", "50:5", "προϊστάμενος"): (NI, "", "no", "falso positivo"),
    ("1Clem", "51:5", "ἡγούμενος"): (NI, "", "no", "jefes de Egipto"),
    ("1Clem", "54:2", "προϊστάμενος"): (NI, "", "no", "falso positivo"),
    ("1Clem", "54:2", "πρεσβύτερος"): ("cargo", "colegio;eleccion", "no", "μετὰ τῶν καθεσταμένων πρεσβυτέρων: presbíteros instituidos"),
    ("1Clem", "55:1", "ἡγούμενος"): (NI, "", "no", "reyes y gobernantes paganos"),
    ("1Clem", "55:4", "πρεσβύτερος"): (NI, "", "no", "los ancianos de la ciudad (Judit)"),
    ("1Clem", "56:13", "οἶκος"): (NI, "", "no", "Jb 5,24"),
    ("1Clem", "57:1", "πρεσβύτερος"): ("cargo", "colegio;disciplina", "no", "ὑποτάγητε τοῖς πρεσβυτέροις καὶ παιδεύθητε εἰς μετάνοιαν: sumisión de los sediciosos a los presbíteros"),
    ("1Clem", "58:2", "προϊστάμενος"): (NI, "", "no", "falso positivo"),
    ("1Clem", "59:3", "ἐπίσκοπος"): (NI, "", "no", "Dios ἐπίσκοπος πάσης σαρκός"),
    ("1Clem", "60:4", "ἡγούμενος"): (NI, "", "no", "gobernantes civiles (oración)"),
    ("1Clem", "61:3", "προϊστάμενος"): (NI, "", "no", "Cristo ἀρχιερεὺς καὶ προστάτης"),
    ("1Clem", "64:1", "προϊστάμενος"): (NI, "", "no", "Cristo ἀρχιερεὺς καὶ προστάτης"),
    # ===== Didajé =====
    ("Did", "4:13", "προϊστάμενος"): (NI, "", "no", "προστίθημι, falso positivo"),
    ("Did", "4:14", "ἐκκλησία"): ("reunion", "", "no", "ἐν ἐκκλησίᾳ ἐξομολογήσῃ τὰ παραπτώματά σου"),
    ("Did", "9:4", "ἐκκλησία"): ("universal", "", "no", "συναχθήτω σου ἡ ἐκκλησία ἀπὸ τῶν περάτων τῆς γῆς"),
    ("Did", "10:5", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Did", "11:11", "ἐκκλησία"): (NI, "", "sí", "μυστήριον κοσμικὸν ἐκκλησίας (pasaje oscuro)"),
    ("Did", "15:1", "χειροτονία"): ("rito", "eleccion", "sí", "χειροτονήσατε οὖν ἑαυτοῖς ἐπισκόπους καὶ διακόνους: elección por la comunidad (juicio: elección, no rito de manos)"),
    ("Did", "15:1", "ἐπίσκοπος"): ("cargo", "eleccion;requisitos;colegio", "no", "ἄνδρας πραεῖς καὶ ἀφιλαργύρους καὶ ἀληθεῖς καὶ δεδοκιμασμένους"),
    ("Did", "15:1", "διάκονος"): ("cargo", "eleccion;requisitos;colegio", "no", ""),
    # ===== Policarpo =====
    ("PolFil", "0:1", "πρεσβύτερος"): ("cargo", "colegio", "no", "Πολύκαρπος καὶ οἱ σὺν αὐτῷ πρεσβύτεροι: Policarpo escribe con su colegio, sin el título de ἐπίσκοπος"),
    ("PolFil", "0:1", "ἐκκλησία"): ("local", "", "no", "prescripto"),
    ("PolFil", "4:3", "χήρα"): ("categoria", "requisitos", "sí", "τὰς χήρας σωφρονούσας … θυσιαστήριον θεοῦ: las viudas como grupo con conducta exigida (juicio)"),
    ("PolFil", "5:2", "διάκονος"): ("cargo", "requisitos", "no", "ὁμοίως διάκονοι ἄμεμπτοι … μὴ διάβολοι, μὴ δίλογοι, ἀφιλάργυροι: lista de requisitos"),
    ("PolFil", "5:2", "διάκονος", "διάκονοσ"): (NI, "", "no", "Cristo διάκονος πάντων"),
    ("PolFil", "5:3", "νεώτερος"): ("categoria", "requisitos", "no", "ὁμοίως καὶ νεώτεροι ἄμεμπτοι ἐν πᾶσιν: los jóvenes como grupo"),
    ("PolFil", "5:3", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "sí", "ὑποτασσομένους τοῖς πρεσβυτέροις καὶ διακόνοις ὡς θεῷ καὶ Χριστῷ: sumisión de los jóvenes a presbíteros y diáconos (juicio: jerarquía entre cargos o entre fieles y cargos)"),
    ("PolFil", "5:3", "διάκονος"): ("cargo", "colegio", "no", ""),
    ("PolFil", "6:1", "πρεσβύτερος"): ("cargo", "requisitos;colegio", "no", "καὶ οἱ πρεσβύτεροι δὲ εὔσπλαγχνοι, εἰς πάντας ἐλεήμονες…: requisitos de los presbíteros"),
    ("PolFil", "6:1", "χήρα"): (NI, "", "no", "μὴ ἀμελοῦντες χήρας ἢ ὀρφανοῦ ἢ πένητος: cuidado genérico"),
    # ===== Ignacio =====
    ("IgnEf", "0:1", "ἐκκλησία"): ("local", "", "no", "prescripto"),
    ("IgnEf", "1:3", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", "Onésimo, ὑμῶν ἐπίσκοπος (singular con nombre)"),
    ("IgnEf", "2:1", "διάκονος"): ("cargo", "", "no", "Burro, διάκονος ὑμῶν"),
    ("IgnEf", "2:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", ""),
    ("IgnEf", "2:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "ὑποτασσόμενοι τῷ ἐπισκόπῳ καὶ τῷ πρεσβυτερίῳ"),
    ("IgnEf", "2:2", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnEf", "3:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", "οἱ ἐπίσκοποι οἱ κατὰ τὰ πέρατα ὁρισθέντες: un obispo por lugar"),
    ("IgnEf", "4:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "συντρέχειν τῇ τοῦ ἐπισκόπου γνώμῃ; τὸ πρεσβυτέριον … συνήρμοσται τῷ ἐπισκόπῳ"),
    ("IgnEf", "4:1", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnEf", "5:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", ""),
    ("IgnEf", "5:1", "ἐκκλησία"): ("universal", "", "sí", "ὡς ἡ ἐκκλησία Ἰησοῦ Χριστῷ"),
    ("IgnEf", "5:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", "ἡ τοῦ ἐπισκόπου καὶ πάσης τῆς ἐκκλησίας (προσευχή)"),
    ("IgnEf", "5:2", "ἐκκλησία"): ("local", "", "no", ""),
    ("IgnEf", "5:3", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "μὴ ἀντιτάσσεσθαι τῷ ἐπισκόπῳ"),
    ("IgnEf", "6:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "τὸν οὖν ἐπίσκοπον δῆλον ὅτι ὡς αὐτὸν τὸν κύριον δεῖ προσβλέπειν"),
    ("IgnEf", "8:1", "ἐκκλησία"): ("local", "", "no", ""),
    ("IgnEf", "17:1", "ἐκκλησία"): ("universal", "", "no", ""),
    ("IgnEf", "20:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "ὑπακούειν ὑμᾶς τῷ ἐπισκόπῳ καὶ τῷ πρεσβυτερίῳ"),
    ("IgnEf", "20:2", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnEf", "21:2", "ἐκκλησία"): ("local", "", "no", "la iglesia de Siria"),
    ("IgnMagn", "0:1", "ἐκκλησία"): ("local", "", "no", "prescripto"),
    ("IgnMagn", "1:2", "ἐκκλησία"): ("local", "", "no", "τὰς ἐκκλησίας"),
    ("IgnMagn", "2:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "Damas ἐπίσκοπος, presbíteros Baso y Apolonio, diácono Zotión, ὑποτάσσεται τῷ ἐπισκόπῳ … καὶ τῷ πρεσβυτερίῳ"),
    ("IgnMagn", "2:1", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnMagn", "2:1", "διάκονος"): ("cargo", "jerarquia", "no", "el diácono sometido a obispo y presbiterio"),
    ("IgnMagn", "3:1", "ἐπίσκοπος", "ἐπισκόπου"): ("cargo", "monoepiscopado", "no", "μὴ συγχρᾶσθαι τῇ ἡλικίᾳ τοῦ ἐπισκόπου: obispo joven"),
    ("IgnMagn", "3:1", "ἐπίσκοπος", "ἐπισκόπῳ"): (NI, "", "no", "el Padre, τῷ πάντων ἐπισκόπῳ"),
    ("IgnMagn", "3:1", "πρεσβύτερος"): ("cargo", "colegio", "no", "τοὺς ἁγίους πρεσβυτέρους"),
    ("IgnMagn", "3:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", ""),
    ("IgnMagn", "4:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;disciplina", "sí", "τινες ἐπίσκοπον μὲν καλοῦσιν, χωρὶς δὲ αὐτοῦ πάντα πράσσουσιν: actuar sin el obispo, censurado (juicio: disciplina)"),
    ("IgnMagn", "6:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "προκαθημένου τοῦ ἐπισκόπου εἰς τόπον θεοῦ καὶ τῶν πρεσβυτέρων εἰς τόπον συνεδρίου τῶν ἀποστόλων καὶ τῶν διακόνων"),
    ("IgnMagn", "6:1", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnMagn", "6:1", "διάκονος"): ("cargo", "jerarquia", "no", "διακόνων … πεπιστευμένων διακονίαν Ἰησοῦ Χριστοῦ"),
    ("IgnMagn", "6:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", ""),
    ("IgnMagn", "7:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "μηδὲ ὑμεῖς ἄνευ τοῦ ἐπισκόπου καὶ τῶν πρεσβυτέρων μηδὲν πράσσετε"),
    ("IgnMagn", "7:1", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnMagn", "13:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", ""),
    ("IgnMagn", "13:1", "πρεσβύτερος"): ("cargo", "colegio", "no", "στεφάνου τοῦ πρεσβυτερίου"),
    ("IgnMagn", "13:1", "διάκονος"): ("cargo", "", "no", ""),
    ("IgnMagn", "13:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "ὑποτάγητε τῷ ἐπισκόπῳ καὶ ἀλλήλοις"),
    ("IgnMagn", "14:1", "ἐκκλησία"): ("local", "", "no", "la iglesia de Siria; la de Magnesia"),
    ("IgnMagn", "15:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", "Πολυκάρπῳ ἐπισκόπῳ Σμυρναίων"),
    ("IgnMagn", "15:1", "ἐκκλησία"): ("local", "", "no", ""),
    ("IgnTral", "0:1", "ἐκκλησία"): ("local", "", "no", "prescripto"),
    ("IgnTral", "1:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", "Polibio ὁ ἐπίσκοπος ὑμῶν"),
    ("IgnTral", "2:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "τῷ ἐπισκόπῳ ὑποτάσσησθε ὡς Ἰησοῦ Χριστῷ"),
    ("IgnTral", "2:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "ἄνευ τοῦ ἐπισκόπου μηδὲν πράσσειν"),
    ("IgnTral", "2:2", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", "ὑποτάσσεσθαι καὶ τῷ πρεσβυτερίῳ ὡς τοῖς ἀποστόλοις"),
    ("IgnTral", "2:3", "διάκονος"): ("cargo", "requisitos", "sí", "δεῖ δὲ καὶ τοὺς διακόνους ὄντας μυστηρίων Ἰησοῦ Χριστοῦ κατὰ πάντα τρόπον πᾶσιν ἀρέσκειν: exigencia general (juicio: requisitos)"),
    ("IgnTral", "2:3", "ἐκκλησία"): ("local", "", "no", "ἐκκλησίας θεοῦ ὑπηρέται"),
    ("IgnTral", "3:1", "διάκονος"): ("cargo", "jerarquia", "no", "πάντες ἐντρεπέσθωσαν τοὺς διακόνους ὡς Ἰησοῦν Χριστόν, ὡς καὶ τὸν ἐπίσκοπον … τοὺς δὲ πρεσβυτέρους ὡς συνέδριον θεοῦ"),
    ("IgnTral", "3:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", ""),
    ("IgnTral", "3:1", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnTral", "3:1", "ἐκκλησία"): ("universal", "", "sí", "χωρὶς τούτων ἐκκλησία οὐ καλεῖται: sin los tres cargos no hay iglesia"),
    ("IgnTral", "3:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", ""),
    ("IgnTral", "7:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", "ἀχωρίστοις θεοῦ Ἰησοῦ Χριστοῦ καὶ τοῦ ἐπισκόπου"),
    ("IgnTral", "7:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "ὁ χωρὶς ἐπισκόπου καὶ πρεσβυτερίου καὶ διακόνων πράσσων τι, οὗτος οὐ καθαρός ἐστιν"),
    ("IgnTral", "7:2", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnTral", "7:2", "διάκονος"): ("cargo", "jerarquia", "no", ""),
    ("IgnTral", "12:1", "ἐκκλησία"): ("local", "", "no", ""),
    ("IgnTral", "12:2", "πρεσβύτερος"): ("cargo", "colegio", "no", ""),
    ("IgnTral", "12:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", ""),
    ("IgnTral", "13:1", "ἐκκλησία"): ("local", "", "no", ""),
    ("IgnTral", "13:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "ὑποτασσόμενοι τῷ ἐπισκόπῳ ὡς τῇ ἐντολῇ, ὁμοίως καὶ τῷ πρεσβυτερίῳ"),
    ("IgnTral", "13:2", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnRom", "0:1", "ἐκκλησία"): ("local", "", "no", "prescripto"),
    ("IgnRom", "2:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", "τὸν ἐπίσκοπον Συρίας (Ignacio)"),
    ("IgnRom", "4:1", "ἐκκλησία"): ("local", "", "no", "πάσαις ταῖς ἐκκλησίαις"),
    ("IgnRom", "9:1", "ἐπίσκοπος"): (NI, "", "no", "Ἰησοῦς Χριστὸς ἐπισκοπήσει (verbo, Cristo)"),
    ("IgnRom", "9:1", "ἐκκλησία"): ("local", "", "no", "la iglesia de Siria"),
    ("IgnFil", "0:1", "ἐκκλησία"): ("local", "", "no", "prescripto"),
    ("IgnFil", "0:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "σὺν τῷ ἐπισκόπῳ καὶ τοῖς σὺν αὐτῷ πρεσβυτέροις καὶ διακόνοις ἀποδεδειγμένοις ἐν γνώμῃ Ἰησοῦ Χριστοῦ"),
    ("IgnFil", "0:1", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnFil", "0:1", "διάκονος"): ("cargo", "eleccion", "sí", "ἀποδεδειγμένοις: designados (juicio: elección o institución)"),
    ("IgnFil", "1:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", "ὃν ἐπίσκοπον ἔγνων … κεκτῆσθαι τὴν διακονίαν τὴν εἰς τὸ κοινὸν ἀνήκουσαν"),
    ("IgnFil", "1:1", "διάκονος"): ("funcion", "", "no", "la διακονία del obispo"),
    ("IgnFil", "3:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", "ὅσοι … θεοῦ εἰσιν καὶ Ἰησοῦ Χριστοῦ, οὗτοι μετὰ τοῦ ἐπισκόπου εἰσίν"),
    ("IgnFil", "3:2", "ἐκκλησία"): ("universal", "", "sí", "ἡ ἑνότης τῆς ἐκκλησίας"),
    ("IgnFil", "4:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "ἓν θυσιαστήριον, ὡς εἷς ἐπίσκοπος ἅμα τῷ πρεσβυτερίῳ καὶ διακόνοις"),
    ("IgnFil", "4:1", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnFil", "4:1", "διάκονος"): ("cargo", "jerarquia", "no", ""),
    ("IgnFil", "5:1", "πρεσβύτερος"): ("cargo", "colegio", "sí", "τοῖς ἀποστόλοις ὡς πρεσβυτερίῳ ἐκκλησίας: comparación (juicio)"),
    ("IgnFil", "5:1", "ἐκκλησία"): ("universal", "", "sí", ""),
    ("IgnFil", "7:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "τῷ ἐπισκόπῳ προσέχετε καὶ τῷ πρεσβυτερίῳ καὶ διακόνοις"),
    ("IgnFil", "7:1", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnFil", "7:1", "διάκονος"): ("cargo", "jerarquia", "no", ""),
    ("IgnFil", "7:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "χωρὶς τοῦ ἐπισκόπου μηδὲν ποιεῖτε"),
    ("IgnFil", "8:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", "συνέδριον τοῦ ἐπισκόπου"),
    ("IgnFil", "9:1", "ἐκκλησία"): ("universal", "", "no", ""),
    ("IgnFil", "10:1", "ἐκκλησία", "ἐκκλησίαν"): ("local", "", "no", "la iglesia de Antioquía"),
    ("IgnFil", "10:1", "ἐκκλησία", "ἐκκλησίᾳ"): ("local", "", "no", ""),
    ("IgnFil", "10:1", "χειροτονία"): ("funcion", "eleccion", "no", "χειροτονῆσαι διάκονον εἰς τὸ πρεσβεῦσαι ἐκεῖ θεοῦ πρεσβείαν: elección de un enviado, no rito"),
    ("IgnFil", "10:1", "διάκονος"): ("funcion", "eleccion", "sí", "διάκονον = enviado (juicio: cargo o función)"),
    ("IgnFil", "10:2", "διάκονος"): ("funcion", "", "no", "τῆς τοιαύτης διακονίας (embajada)"),
    ("IgnFil", "10:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", "αἱ ἔγγιστα ἐκκλησίαι ἔπεμψαν ἐπισκόπους, αἱ δὲ πρεσβυτέρους καὶ διακόνους"),
    ("IgnFil", "10:2", "πρεσβύτερος"): ("cargo", "colegio", "no", ""),
    ("IgnFil", "10:2", "διάκονος", "διακόνουσ"): ("cargo", "", "no", ""),
    ("IgnFil", "10:2", "ἐκκλησία"): ("local", "", "no", ""),
    ("IgnFil", "11:1", "διάκονος"): ("cargo", "", "no", "Filón, διάκονος de Cilicia"),
    ("IgnEsm", "0:1", "ἐκκλησία"): ("local", "", "no", "prescripto"),
    ("IgnEsm", "1:2", "ἐκκλησία"): ("universal", "", "no", "ἐν ἑνὶ σώματι τῆς ἐκκλησίας αὐτοῦ"),
    ("IgnEsm", "6:2", "χήρα"): (NI, "", "no", "cuidado genérico de viudas y huérfanos"),
    ("IgnEsm", "8:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "πάντες τῷ ἐπισκόπῳ ἀκολουθεῖτε … μηδεὶς χωρὶς τοῦ ἐπισκόπου τι πρασσέτω; εὐχαριστία ἡ ὑπὸ ἐπίσκοπον οὖσα"),
    ("IgnEsm", "8:1", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnEsm", "8:1", "διάκονος"): ("cargo", "jerarquia", "no", "τοὺς δὲ διακόνους ἐντρέπεσθε ὡς θεοῦ ἐντολήν"),
    ("IgnEsm", "8:1", "ἐκκλησία"): ("local", "", "no", ""),
    ("IgnEsm", "8:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "ὅπου ἂν φανῇ ὁ ἐπίσκοπος, ἐκεῖ τὸ πλῆθος ἔστω … οὐκ ἐξόν ἐστιν χωρὶς τοῦ ἐπισκόπου οὔτε βαπτίζειν οὔτε ἀγάπην ποιεῖν"),
    ("IgnEsm", "8:2", "ἐκκλησία"): ("universal", "", "no", "ἡ καθολικὴ ἐκκλησία"),
    ("IgnEsm", "9:1", "ἐπίσκοπος"): ("cargo", "monoepiscopado;jerarquia", "no", "ὁ τιμῶν ἐπίσκοπον ὑπὸ θεοῦ τετίμηται· ὁ λάθρα ἐπισκόπου τι πράσσων τῷ διαβόλῳ λατρεύει"),
    ("IgnEsm", "10:1", "διάκονος"): ("cargo", "", "sí", "Filón y Reo Agatópode ὡς διακόνους θεοῦ (juicio: Filón es diácono, IgnFil 11,1)"),
    ("IgnEsm", "11:1", "ἐκκλησία"): ("local", "", "no", ""),
    ("IgnEsm", "11:2", "χειροτονία"): ("funcion", "eleccion", "no", "χειροτονῆσαι τὴν ἐκκλησίαν ὑμῶν θεοπρεσβευτήν: elección de un enviado"),
    ("IgnEsm", "11:2", "ἐκκλησία"): ("reunion", "", "no", "la comunidad elige"),
    ("IgnEsm", "12:1", "διάκονος"): ("funcion", "", "no", "Burro ἐξεμπλάριον θεοῦ διακονίας"),
    ("IgnEsm", "12:2", "ἐπίσκοπος"): ("cargo", "monoepiscopado", "no", ""),
    ("IgnEsm", "12:2", "πρεσβύτερος"): ("cargo", "colegio", "no", ""),
    ("IgnEsm", "12:2", "διάκονος"): ("cargo", "", "no", "τοὺς συνδούλους μου διακόνους"),
    ("IgnEsm", "13:1", "χήρα"): ("categoria", "", "no", "τὰς παρθένους τὰς λεγομένας χήρας: categoría reconocida con nombre técnico"),
    ("IgnEsm", "13:1", "οἶκος"): ("celula", "", "sí", "ἀσπάζομαι τοὺς οἴκους τῶν ἀδελφῶν μου: las casas como unidades de saludo"),
    ("IgnEsm", "13:2", "οἶκος"): ("celula", "", "sí", "τὸν οἶκον Ταουΐας"),
    ("IgnPol", "0:1", "ἐπίσκοπος", "ἐπισκόπῳ"): ("cargo", "monoepiscopado", "no", "Πολυκάρπῳ ἐπισκόπῳ ἐκκλησίας Σμυρναίων"),
    ("IgnPol", "0:1", "ἐπίσκοπος", "ἐπισκοπημένῳ"): (NI, "", "no", "ἐπισκοπημένῳ ὑπὸ θεοῦ (verbo)"),
    ("IgnPol", "0:1", "ἐκκλησία"): ("local", "", "no", ""),
    ("IgnPol", "4:1", "χήρα"): ("categoria", "", "no", "χῆραι μὴ ἀμελείσθωσαν· μετὰ τὸν κύριον σὺ αὐτῶν φροντιστὴς ἔσο: el obispo, responsable de las viudas"),
    ("IgnPol", "5:1", "ἐκκλησία"): ("universal", "", "no", ""),
    ("IgnPol", "5:2", "ἐπίσκοπος", "ἐπισκόπου"): ("cargo", "monoepiscopado;jerarquia", "no", "ἐὰν γνωσθῇ πλέον τοῦ ἐπισκόπου, ἔφθαρται; τοῖς γαμοῦσι … μετὰ γνώμης τοῦ ἐπισκόπου τὴν ἕνωσιν ποιεῖσθαι"),
    ("IgnPol", "6:1", "ἐπίσκοπος", "ἐπισκόπῳ"): ("cargo", "monoepiscopado;jerarquia", "no", "τῷ ἐπισκόπῳ προσέχετε; τῶν ὑποτασσομένων τῷ ἐπισκόπῳ, πρεσβυτέροις, διακόνοις"),
    ("IgnPol", "6:1", "πρεσβύτερος"): ("cargo", "colegio;jerarquia", "no", ""),
    ("IgnPol", "6:1", "διάκονος"): ("cargo", "jerarquia", "no", ""),
    ("IgnPol", "7:1", "ἐκκλησία"): ("local", "", "no", "la iglesia de Antioquía"),
    ("IgnPol", "7:2", "χειροτονία"): ("funcion", "eleccion", "no", "συμβούλιον ἀγαγεῖν θεοπρεπέστατον καὶ χειροτονῆσαί τινα: elección de un enviado"),
    ("IgnPol", "8:1", "προϊστάμενος"): (NI, "", "no", "προστάσσω, falso positivo"),
    ("IgnPol", "8:1", "ἐκκλησία"): ("local", "", "no", ""),
    ("IgnPol", "8:2", "οἶκος"): ("celula", "", "sí", "σὺν ὅλῳ τῷ οἴκῳ αὐτῆς καὶ τῶν τέκνων"),
    ("IgnPol", "8:3", "ἐπίσκοπος"): ("funcion", "", "sí", "ἐν ἑνότητι θεοῦ καὶ ἐπισκοπῇ: supervisión (de Dios o del obispo; juicio)"),
    # ===== Hermas =====
    ("Herm", "1.1:6", "ἐκκλησία"): ("universal", "", "no", "ἡ ἁγία ἐκκλησία"),
    ("Herm", "1.1:9", "οἶκος"): (NI, "", "no", "la familia de Hermas"),
    ("Herm", "1.3:1", "οἶκος"): (NI, "", "no", "la familia de Hermas"),
    ("Herm", "1.3:2", "οἶκος"): (NI, "", "no", ""),
    ("Herm", "1.3:4", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Herm", "2.1:3", "πρεσβύτερος"): (NI, "", "no", "ἡ πρεσβυτέρα: la anciana (la Iglesia personificada)"),
    ("Herm", "2.2:6", "ἐκκλησία"): ("local", "", "no", "τοῖς προηγουμένοις τῆς ἐκκλησίας"),
    ("Herm", "2.3:1", "οἶκος"): (NI, "", "no", ""),
    ("Herm", "2.4:1", "πρεσβύτερος"): (NI, "", "no", "la anciana"),
    ("Herm", "2.4:1", "ἐκκλησία"): ("universal", "", "no", "la anciana es la Iglesia"),
    ("Herm", "2.4:2", "πρεσβύτερος", "πρεσβυτέρα"): (NI, "", "no", "la anciana"),
    ("Herm", "2.4:2", "πρεσβύτερος", "πρεσβυτέροισ"): ("cargo", "colegio", "no", "εἰ ἤδη τὸ βιβλίον δέδωκα τοῖς πρεσβυτέροις: los presbíteros reciben el libro"),
    ("Herm", "2.4:2", "οἶκος"): (NI, "", "no", ""),
    ("Herm", "2.4:3", "χήρα"): ("categoria", "", "sí", "Γραπτὴ δὲ νουθετήσει τὰς χήρας καὶ τοὺς ὀρφανούς: viudas y huérfanos como grupo a cargo de una mujer (juicio)"),
    ("Herm", "2.4:3", "πρεσβύτερος"): ("cargo", "colegio", "no", "μετὰ τῶν πρεσβυτέρων τῶν προϊσταμένων τῆς ἐκκλησίας"),
    ("Herm", "2.4:3", "προϊστάμενος"): ("cargo", "colegio", "no", "presbíteros que presiden la iglesia"),
    ("Herm", "2.4:3", "ἐκκλησία"): ("local", "", "no", "la iglesia de Roma"),
    ("Herm", "3.1:2", "πρεσβύτερος"): (NI, "", "no", "la anciana"),
    ("Herm", "3.1:8", "πρεσβύτερος"): ("cargo", "colegio", "sí", "ἄφες τοὺς πρεσβυτέρους πρῶτον καθίσαι: precedencia de los presbíteros (juicio: cargo o edad)"),
    ("Herm", "3.3:3", "ἐκκλησία"): ("universal", "", "no", "la torre"),
    ("Herm", "3.5:1", "ἐπίσκοπος", "ἐπίσκοποι"): ("cargo", "colegio", "no", "οἱ ἀπόστολοι καὶ ἐπίσκοποι καὶ διδάσκαλοι καὶ διάκονοι"),
    ("Herm", "3.5:1", "ἐπίσκοπος", "ἐπισκοπήσαντεσ"): ("funcion", "", "no", "ἐπισκοπήσαντες καὶ διδάξαντες καὶ διακονήσαντες"),
    ("Herm", "3.5:1", "διάκονος", "διάκονοι"): ("cargo", "colegio", "no", ""),
    ("Herm", "3.5:1", "διάκονος", "διακονήσαντεσ"): ("funcion", "", "no", ""),
    ("Herm", "3.9:7", "ἐκκλησία"): ("local", "", "no", "τοῖς προηγουμένοις τῆς ἐκκλησίας καὶ τοῖς πρωτοκαθεδρίταις"),
    ("Herm", "3.10:3", "πρεσβύτερος"): (NI, "", "no", "la anciana"),
    ("Herm", "3.10:4", "νεώτερος"): (NI, "", "no", "aspecto joven de la anciana"),
    ("Herm", "3.10:4", "πρεσβύτερος"): (NI, "", "no", ""),
    ("Herm", "3.10:5", "νεώτερος"): (NI, "", "no", ""),
    ("Herm", "3.10:5", "πρεσβύτερος"): (NI, "", "no", ""),
    ("Herm", "3.10:6", "πρεσβύτερος"): (NI, "", "no", ""),
    ("Herm", "3.10:9", "πρεσβύτερος"): (NI, "", "no", ""),
    ("Herm", "3.11:2", "πρεσβύτερος"): (NI, "", "no", ""),
    ("Herm", "3.11:3", "πρεσβύτερος"): (NI, "", "no", "los ancianos de edad"),
    ("Herm", "3.12:1", "νεώτερος"): (NI, "", "no", ""),
    ("Herm", "3.12:1", "πρεσβύτερος"): (NI, "", "no", ""),
    ("Herm", "3.12:2", "πρεσβύτερος"): (NI, "", "no", "parábola del anciano"),
    ("Herm", "3.13:1", "νεώτερος"): (NI, "", "no", ""),
    ("Herm", "4.1:3", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Herm", "4.2:2", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Herm", "5.1:1", "οἶκος"): (NI, "", "no", ""),
    ("Herm", "7.1:6", "διάκονος"): (NI, "", "no", "la limosna como διακονία"),
    ("Herm", "7.1:7", "οἶκος"): (NI, "", "no", ""),
    ("Herm", "13.1:10", "χήρα"): (NI, "", "no", "χήραις ὑπηρετεῖν: obra de caridad genérica"),
    ("Herm", "17.3:3", "διάκονος"): (NI, "", "no", "servicio de los ricos"),
    ("Herm", "17.6:2", "προϊστάμενος"): (NI, "", "no", "προστίθημι, falso positivo"),
    ("Herm", "18.1:8", "χήρα"): (NI, "", "no", "caridad genérica"),
    ("Herm", "18.1:9", "διάκονος"): (NI, "", "no", ""),
    ("Herm", "18.1:9", "οἶκος"): (NI, "", "no", "casas como bienes"),
    ("Herm", "19.1:7", "διάκονος"): (NI, "", "no", ""),
    ("Herm", "19.1:10", "διάκονος"): (NI, "", "no", ""),
    ("Herm", "22.1:5", "προϊστάμενος"): (NI, "", "no", "falso positivo"),
    ("Herm", "22.3:7", "χήρα"): (NI, "", "no", "ayuno y limosna"),
    ("Herm", "22.3:9", "οἶκος"): (NI, "", "no", ""),
    ("Herm", "23.1:1", "οἶκος"): (NI, "", "no", ""),
    ("Herm", "23.1:4", "προϊστάμενος"): (NI, "", "no", "falso positivo"),
    ("Herm", "24.1:1", "οἶκος"): (NI, "", "no", ""),
    ("Herm", "24.1:3", "οἶκος"): (NI, "", "no", "Hermas cabeza de familia"),
    ("Herm", "24.1:5", "οἶκος"): (NI, "", "no", ""),
    ("Herm", "24.1:7", "οἶκος"): (NI, "", "no", ""),
    ("Herm", "25.4:1", "διάκονος"): (NI, "", "no", "servir la comida"),
    ("Herm", "25.4:2", "διάκονος"): (NI, "", "no", ""),
    ("Herm", "25.6:4", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Herm", "25.10:3", "οἶκος"): (NI, "", "no", "hospitalidad"),
    ("Herm", "26.1:1", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Herm", "26.1:2", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Herm", "26.11:2", "οἶκος"): (NI, "", "no", ""),
    ("Herm", "26.11:5", "νεώτερος"): (NI, "", "no", ""),
    ("Herm", "26.11:6", "οἶκος"): (NI, "", "no", ""),
    ("Herm", "26.13:1", "ἐκκλησία"): ("universal", "", "no", "la torre es la Iglesia"),
    ("Herm", "26.13:9", "οἶκος"): (NI, "", "sí", "ὁ οἶκος τοῦ θεοῦ: metáfora de la Iglesia"),
    ("Herm", "26.14:1", "οἶκος"): (NI, "", "sí", "metáfora"),
    ("Herm", "26.15:4", "διάκονος"): ("funcion", "", "sí", "οἱ προφῆται τοῦ θεοῦ καὶ διάκονοι αὐτοῦ (las 35 piedras): ministros de Dios en general (juicio)"),
    ("Herm", "26.18:2", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Herm", "26.18:3", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Herm", "26.18:4", "ἐκκλησία"): ("universal", "", "no", ""),
    ("Herm", "26.26:2", "διάκονος", "διάκονοί"): ("cargo", "disciplina", "no", "διάκονοί εἰσι κακῶς διακονήσαντες καὶ διαρπάσαντες χηρῶν καὶ ὀρφανῶν τὴν ζωήν: diáconos que administran mal los fondos; deben enmendarse"),
    ("Herm", "26.26:2", "διάκονος", "διακονήσαντεσ"): ("cargo", "", "no", "ejercicio del cargo"),
    ("Herm", "26.26:2", "διάκονος", "διακονίασ"): ("cargo", "", "no", "ἐκ τῆς διακονίας ἧς ἔλαβον διακονῆσαι"),
    ("Herm", "26.26:2", "διάκονος", "διακονῆσαι"): ("cargo", "", "no", ""),
    ("Herm", "26.26:2", "διάκονος", "διακονίαν"): ("cargo", "", "no", "τελειώσωσι τὴν διακονίαν αὐτῶν"),
    ("Herm", "26.26:2", "χήρα"): ("categoria", "", "sí", "las viudas y huérfanos como beneficiarios de los fondos administrados por los diáconos (juicio)"),
    ("Herm", "26.27:2", "ἐπίσκοπος"): ("cargo", "colegio", "no", "ἐπίσκοποι καὶ φιλόξενοι … οἱ δὲ ἐπίσκοποι πάντοτε τοὺς ὑστερημένους καὶ τὰς χήρας τῇ διακονίᾳ ἑαυτῶν ἀδιαλείπτως ἐσκέπασαν: plural, función asistencial"),
    ("Herm", "26.27:2", "χήρα"): ("categoria", "", "sí", "viudas asistidas por los obispos (juicio)"),
    ("Herm", "26.27:2", "διάκονος"): ("funcion", "", "no", "τῇ διακονίᾳ ἑαυτῶν: el servicio de los obispos"),
    ("Herm", "26.27:2", "οἶκος"): (NI, "", "no", "hospitalidad en sus casas"),
}
