# -*- coding: utf-8 -*-
"""Clasificación manual de los lemas con mayúscula de las catorce cartas (MorphGNT) para el inventario onomástico
(docs/canales/codigos_onomastica.md § 1). Codificador único (enmienda 6). Fuentes: el texto de las cartas (SBLGNT),
Hechos de los Apóstoles (SBLGNT) para `b_hechos`, y el propio corpus para `a_otra_carta`.

TIPO: persona (contemporánea del documento), biblico (personaje del AT o figura legendaria: famoso), historico (personaje
de la historia conocida: famoso), lugar, pueblo, divinidad, otro (se excluyen del inventario de personas)."""

# lema MorphGNT → (nombre_es, tipo, b_hechos, nota_b)
NOMBRES = {
    # ---- personas contemporáneas ----
    "Παῦλος": ("Pablo", "persona", 1, "Hch 13-28"), "Τιμόθεος": ("Timoteo", "persona", 1, "Hch 16,1-3; 17,14-15; 18,5; 19,22; 20,4"),
    "Τίτος": ("Tito", "persona", 0, "no aparece en Hechos"), "Σιλουανός": ("Silvano (Silas)", "persona", 1, "Hch 15,22-18,5 (Σιλᾶς)"),
    "Ἀπολλῶς": ("Apolo", "persona", 1, "Hch 18,24-19,1"), "Κηφᾶς": ("Cefas (Pedro)", "persona", 1, "Hch 1-15 (Πέτρος)"),
    "Πέτρος": ("Pedro", "persona", 1, "Hch 1-15"), "Ἰάκωβος": ("Santiago (hermano del Señor)", "persona", 1, "Hch 12,17; 15,13; 21,18"),
    "Ἰωάννης": ("Juan (apóstol)", "persona", 1, "Hch 3-4; 8,14"), "Βαρναβᾶς": ("Bernabé", "persona", 1, "Hch 4,36; 9,27; 11-15"),
    "Ἀκύλας": ("Aquila", "persona", 1, "Hch 18,2-3.18-26"), "Πρίσκα": ("Prisca (Priscila)", "persona", 1, "Hch 18,2.18.26 (Πρίσκιλλα)"),
    "Φοίβη": ("Febe", "persona", 0, ""), "Ἐπαίνετος": ("Epéneto", "persona", 0, ""), "Μαριάμ": ("María (Rom 16,6)", "persona", 0, "la María de Hch 12,12 es otra"),
    "Ἀνδρόνικος": ("Andrónico", "persona", 0, ""), "Ἰουνία": ("Junia", "persona", 0, ""), "Ἀμπλιᾶτος": ("Ampliato", "persona", 0, ""),
    "Οὐρβανός": ("Urbano", "persona", 0, ""), "Στάχυς": ("Estaquis", "persona", 0, ""), "Ἀπελλῆς": ("Apeles", "persona", 0, ""),
    "Ἀριστόβουλος": ("Aristóbulo", "persona", 0, ""), "Ἡρῳδίων": ("Herodión", "persona", 0, ""), "Νάρκισσος": ("Narciso", "persona", 0, ""),
    "Τρύφαινα": ("Trifena", "persona", 0, ""), "Τρυφῶσα": ("Trifosa", "persona", 0, ""), "Περσίς": ("Pérside", "persona", 0, ""),
    "Ῥοῦφος": ("Rufo", "persona", 0, "Mc 15,21 (Rufo hijo de Simón de Cirene): identidad no comprobable"), "Ἀσύγκριτος": ("Asíncrito", "persona", 0, ""),
    "Φλέγων": ("Flegonte", "persona", 0, ""), "Ἑρμῆς": ("Hermes (Rom 16,14)", "persona", 0, ""), "Πατροβᾶς": ("Patrobas", "persona", 0, ""),
    "Ἑρμᾶς": ("Hermas", "persona", 0, ""), "Φιλόλογος": ("Filólogo", "persona", 0, ""), "Ἰουλία": ("Julia", "persona", 0, ""),
    "Νηρεύς": ("Nereo", "persona", 0, ""), "Ὀλυμπᾶς": ("Olimpas", "persona", 0, ""), "Λούκιος": ("Lucio", "persona", 0, "Hch 13,1 Lucio de Cirene: identidad dudosa (juicio)"),
    "Ἰάσων": ("Jasón", "persona", 1, "Hch 17,5-9 (Jasón de Tesalónica): identidad probable (juicio)"), "Σωσίπατρος": ("Sosípatro", "persona", 1, "Hch 20,4 Σώπατρος de Berea: identidad probable (juicio)"),
    "Τέρτιος": ("Tercio", "persona", 0, ""), "Γάϊος": ("Gayo", "persona", 1, "Hch 19,29 (Gayo de Macedonia); 20,4 (Gayo de Derbe): identidades distintas; el de Rom/1 Cor es de Corinto (juicio)"),
    "Ἔραστος": ("Erasto", "persona", 1, "Hch 19,22"), "Κούαρτος": ("Cuarto", "persona", 0, ""), "Σωσθένης": ("Sóstenes", "persona", 1, "Hch 18,17 (jefe de sinagoga en Corinto): identidad posible (juicio)"),
    "Χλόη": ("Cloe", "persona", 0, ""), "Κρίσπος": ("Crispo", "persona", 1, "Hch 18,8"), "Στεφανᾶς": ("Estéfanas", "persona", 0, ""),
    "Φορτουνᾶτος": ("Fortunato", "persona", 0, ""), "Ἀχαϊκός": ("Acaico", "persona", 0, ""), "Ἐπαφρόδιτος": ("Epafrodito", "persona", 0, ""),
    "Εὐοδία": ("Evodia", "persona", 0, ""), "Συντύχη": ("Síntique", "persona", 0, ""), "Κλήμης": ("Clemente (Flp 4,3)", "persona", 0, ""),
    "Φιλήμων": ("Filemón", "persona", 0, ""), "Ἀπφία": ("Apia", "persona", 0, ""), "Ἄρχιππος": ("Arquipo", "persona", 0, ""),
    "Ὀνήσιμος": ("Onésimo", "persona", 0, ""), "Ἐπαφρᾶς": ("Epafras", "persona", 0, ""), "Μᾶρκος": ("Marcos", "persona", 1, "Hch 12,12.25; 13,13; 15,37-39"),
    "Ἀρίσταρχος": ("Aristarco", "persona", 1, "Hch 19,29; 20,4; 27,2"), "Δημᾶς": ("Demas", "persona", 0, ""), "Λουκᾶς": ("Lucas", "persona", 0, "no nombrado en Hechos"),
    "Τυχικός": ("Tíquico", "persona", 1, "Hch 20,4"), "Ἰοῦστος": ("Jesús Justo (Col 4,11)", "persona", 0, "Hch 18,7 Ticio Justo es otro"), "Νύμφα": ("Ninfa", "persona", 0, ""),
    "Ὑμέναιος": ("Himeneo", "persona", 0, ""), "Ἀλέξανδρος": ("Alejandro", "persona", 1, "Hch 19,33 (Alejandro, judío de Éfeso): identidad posible (juicio)"),
    "Λωΐς": ("Loida", "persona", 0, "Hch 16,1 nombra a la madre de Timoteo sin nombre"), "Εὐνίκη": ("Eunice", "persona", 0, "Hch 16,1 (sin nombre)"),
    "Φύγελος": ("Figelo", "persona", 0, ""), "Ἑρμογένης": ("Hermógenes", "persona", 0, ""), "Ὀνησίφορος": ("Onesíforo", "persona", 0, ""),
    "Φίλητος": ("Fileto", "persona", 0, ""), "Κρήσκης": ("Crescente", "persona", 0, ""), "Κάρπος": ("Carpo", "persona", 0, ""),
    "Τρόφιμος": ("Trófimo", "persona", 1, "Hch 20,4; 21,29"), "Εὔβουλος": ("Eubulo", "persona", 0, ""), "Πούδης": ("Pudente", "persona", 0, ""),
    "Λίνος": ("Lino", "persona", 0, ""), "Κλαυδία": ("Claudia", "persona", 0, ""), "Ἀρτεμᾶς": ("Artemas", "persona", 0, ""), "Ζηνᾶς": ("Zenas", "persona", 0, ""),
    # ---- históricos (famosos) ----
    "Ἁρέτας": ("Aretas IV", "historico", 0, "Hch 9,23-25 no lo nombra"), "Πιλᾶτος": ("Poncio Pilato", "historico", 1, "Hch 3,13; 4,27; 13,28"), "Πόντιος": ("Poncio (praenomen de Pilato)", "otro", 1, ""),
    "Καῖσαρ": ("César (título)", "otro", 0, ""),
    # ---- bíblicos / legendarios (famosos) ----
    "Ἀβραάμ": ("Abrahán", "biblico", 1, ""), "Ἰσαάκ": ("Isaac", "biblico", 1, ""), "Ἰακώβ": ("Jacob", "biblico", 1, ""), "Ἠσαῦ": ("Esaú", "biblico", 1, ""),
    "Σάρρα": ("Sara", "biblico", 1, ""), "Ἁγάρ": ("Agar", "biblico", 1, ""), "Ῥεβέκκα": ("Rebeca", "biblico", 1, ""), "Δαυίδ": ("David", "biblico", 1, ""),
    "Μωϋσῆς": ("Moisés", "biblico", 1, ""), "Ἀαρών": ("Aarón", "biblico", 1, ""), "Ἠσαΐας": ("Isaías", "biblico", 1, ""), "Ὡσηέ": ("Oseas", "biblico", 1, ""),
    "Ἠλίας": ("Elías", "biblico", 1, ""), "Φαραώ": ("Faraón", "biblico", 1, ""), "Ἀδάμ": ("Adán", "biblico", 1, ""), "Εὕα": ("Eva", "biblico", 1, ""),
    "Ἰεσσαί": ("Jesé", "biblico", 1, ""), "Βενιαμίν": ("Benjamín", "biblico", 1, ""), "Λευί": ("Leví", "biblico", 1, ""), "Ἰούδας": ("Judá", "biblico", 1, ""),
    "Μελχισέδεκ": ("Melquisedec", "biblico", 1, ""), "Σαμουήλ": ("Samuel", "biblico", 1, ""), "Γεδεών": ("Gedeón", "biblico", 1, ""), "Βαράκ": ("Barac", "biblico", 1, ""),
    "Σαμψών": ("Sansón", "biblico", 1, ""), "Ἰεφθάε": ("Jefté", "biblico", 1, ""), "Ῥαάβ": ("Rahab", "biblico", 1, ""), "Ἅβελ": ("Abel", "biblico", 1, ""),
    "Κάϊν": ("Caín", "biblico", 1, ""), "Ἑνώχ": ("Henoc", "biblico", 1, ""), "Νῶε": ("Noé", "biblico", 1, ""), "Ἰωσήφ": ("José", "biblico", 1, ""),
    "Ἰάννης": ("Janes", "biblico", 1, "figura legendaria (tradición judía)"), "Ἰαμβρῆς": ("Jambres", "biblico", 1, "figura legendaria"),
    # ---- divinidades y otros ----
    "Ἰησοῦς": ("Jesús", "divinidad", 0, "en Heb 4,8 es Josué (bíblico)"), "Χριστός": ("Cristo", "divinidad", 0, ""), "Σατανᾶς": ("Satanás", "divinidad", 0, ""),
    "Βελιάρ": ("Beliar", "divinidad", 0, ""), "Βάαλ": ("Baal", "divinidad", 0, ""), "Σαβαώθ": ("Sabaot", "divinidad", 0, ""), "Χεροῦβ": ("querubín", "otro", 0, ""),
    "Ἰουδαϊσμός": ("judaísmo", "otro", 0, ""), "Φαρισαῖος": ("fariseo", "otro", 0, ""),
}
LUGARES = {"Αἴγυπτος","Γαλατία","Γόμορρα","Δαλματία","Δαμασκός","Θεσσαλονίκη","Κεγχρεαί","Κιλικία","Κολοσσαί","Κρήτη","Κόρινθος","Λαοδίκεια","Λύστρα","Μίλητος",
           "Μακεδονία","Νικόπολις","Σαλήμ","Σινᾶ","Σιών","Σπανία","Συρία","Σόδομα","Τρῳάς","Φίλιπποι","Ἀθῆναι","Ἀντιόχεια","Ἀραβία","Ἀσία","Ἀχαΐα","Ἔφεσος",
           "Ἰεριχώ","Ἰερουσαλήμ","Ἰκόνιον","Ἰλλυρικόν","Ἰουδαία","Ἰσραήλ","Ἰταλία","Ἱεράπολις","Ἱεροσόλυμα","Ῥώμη"}
PUEBLOS = {"Γαλάτης","Θεσσαλονικεύς","Κορίνθιος","Κρής","Λαοδικεύς","Μακεδών","Σκύθης","Φιλιππήσιος","Ἑβραῖος","Ἕλλην","Ἰσραηλίτης"}

# (documento, lema) → (lugar, funcion, relacion, e_coherencia, nota) para las personas; lo no listado: lugar «—»,
# funcion «mencionado», relacion «—», e «no comprobable».
DETALLE = {
    ("Rom","Παῦλος"): ("Corinto (redacción)","remitente","—","coherente","Rom 15,25-26: viaje a Jerusalén con la colecta, coherente con Hch 20,3-21,17"),
    ("Rom","Φοίβη"): ("Cencreas","mencionado","diaconisa, patrona","coherente","Hch 18,18 sitúa a Pablo en Cencreas"),
    ("Rom","Πρίσκα"): ("Roma","saludado","colaboradora","coherente","Hch 18,2: expulsados de Roma por Claudio; regreso a Roma plausible tras 54"),
    ("Rom","Ἀκύλας"): ("Roma","saludado","colaborador","coherente","Hch 18,2"),
    ("Rom","Ἐπαίνετος"): ("Roma (procedente de Asia)","saludado","primicia de Asia","coherente","Pablo en Asia (Hch 19)"),
    ("Rom","Μαριάμ"): ("Roma","saludado","—","no comprobable",""), ("Rom","Ἀνδρόνικος"): ("Roma","saludado","pariente, prisionero con Pablo","no comprobable",""),
    ("Rom","Ἰουνία"): ("Roma","saludado","pariente, prisionera con Pablo","no comprobable",""), ("Rom","Ἀμπλιᾶτος"): ("Roma","saludado","amado","no comprobable",""),
    ("Rom","Οὐρβανός"): ("Roma","saludado","colaborador","no comprobable",""), ("Rom","Στάχυς"): ("Roma","saludado","amado","no comprobable",""),
    ("Rom","Ἀπελλῆς"): ("Roma","saludado","—","no comprobable",""), ("Rom","Ἀριστόβουλος"): ("Roma","mencionado","(su casa)","no comprobable",""),
    ("Rom","Ἡρῳδίων"): ("Roma","saludado","pariente","no comprobable",""), ("Rom","Νάρκισσος"): ("Roma","mencionado","(su casa)","no comprobable",""),
    ("Rom","Τρύφαινα"): ("Roma","saludado","—","no comprobable",""), ("Rom","Τρυφῶσα"): ("Roma","saludado","—","no comprobable",""),
    ("Rom","Περσίς"): ("Roma","saludado","amada","no comprobable",""), ("Rom","Ῥοῦφος"): ("Roma","saludado","(y su madre)","no comprobable",""),
    ("Rom","Ἀσύγκριτος"): ("Roma","saludado","—","no comprobable",""), ("Rom","Φλέγων"): ("Roma","saludado","—","no comprobable",""),
    ("Rom","Ἑρμῆς"): ("Roma","saludado","—","no comprobable",""), ("Rom","Πατροβᾶς"): ("Roma","saludado","—","no comprobable",""),
    ("Rom","Ἑρμᾶς"): ("Roma","saludado","—","no comprobable",""), ("Rom","Φιλόλογος"): ("Roma","saludado","—","no comprobable",""),
    ("Rom","Ἰουλία"): ("Roma","saludado","—","no comprobable",""), ("Rom","Νηρεύς"): ("Roma","saludado","(y su hermana)","no comprobable",""),
    ("Rom","Ὀλυμπᾶς"): ("Roma","saludado","—","no comprobable",""), ("Rom","Τιμόθεος"): ("Corinto","colaborador","colaborador","coherente","Hch 20,4: Timoteo con Pablo en Grecia"),
    ("Rom","Λούκιος"): ("Corinto","colaborador","pariente","no comprobable",""), ("Rom","Ἰάσων"): ("Corinto","colaborador","pariente","coherente","Hch 17,5-9 (Tesalónica); Hch 20,4 menciona a tesalonicenses con Pablo"),
    ("Rom","Σωσίπατρος"): ("Corinto","colaborador","pariente","coherente","Hch 20,4 Sópatro de Berea con Pablo"),
    ("Rom","Τέρτιος"): ("Corinto","colaborador","amanuense","no comprobable",""), ("Rom","Γάϊος"): ("Corinto","mencionado","hospedador de Pablo","coherente","1 Cor 1,14: Gayo bautizado por Pablo en Corinto"),
    ("Rom","Ἔραστος"): ("Corinto","mencionado","tesorero de la ciudad","coherente","Hch 19,22; 2 Tim 4,20 lo deja en Corinto"),
    ("Rom","Κούαρτος"): ("Corinto","mencionado","hermano","no comprobable",""),
    ("1Cor","Παῦλος"): ("Éfeso (redacción)","remitente","—","coherente","1 Cor 16,8: en Éfeso hasta Pentecostés; Hch 19"),
    ("1Cor","Σωσθένης"): ("Éfeso","remitente","hermano","coherente","Hch 18,17 (Corinto)"), ("1Cor","Χλόη"): ("Corinto","mencionado","(los de Cloe)","no comprobable",""),
    ("1Cor","Ἀπολλῶς"): ("Corinto/Éfeso","mencionado","colaborador","coherente","Hch 18,24-19,1"), ("1Cor","Κηφᾶς"): ("—","mencionado","apóstol","coherente",""),
    ("1Cor","Κρίσπος"): ("Corinto","mencionado","bautizado por Pablo","coherente","Hch 18,8"), ("1Cor","Γάϊος"): ("Corinto","mencionado","bautizado por Pablo","coherente","Rom 16,23"),
    ("1Cor","Στεφανᾶς"): ("Corinto","mencionado","primicia de Acaya","no comprobable",""), ("1Cor","Τιμόθεος"): ("—","colaborador","enviado","coherente","Hch 19,22"),
    ("1Cor","Βαρναβᾶς"): ("—","mencionado","colaborador","coherente","Hch 13-15"), ("1Cor","Ἀκύλας"): ("Éfeso","saludado","colaborador","coherente","Hch 18,18-19.26"),
    ("1Cor","Πρίσκα"): ("Éfeso","saludado","colaboradora","coherente","Hch 18,18-19.26"), ("1Cor","Φορτουνᾶτος"): ("Corinto","mencionado","—","no comprobable",""),
    ("1Cor","Ἀχαϊκός"): ("Corinto","mencionado","—","no comprobable",""), ("1Cor","Ἰάκωβος"): ("—","mencionado","apóstol","coherente",""),
    ("2Cor","Παῦλος"): ("Macedonia (redacción)","remitente","—","coherente","2 Cor 2,13; 7,5; Hch 20,1-2"), ("2Cor","Τιμόθεος"): ("Macedonia","remitente","hermano","coherente","Hch 20,4"),
    ("2Cor","Τίτος"): ("Macedonia/Corinto","colaborador","compañero","no comprobable","Tito no aparece en Hechos"), ("2Cor","Σιλουανός"): ("Corinto","mencionado","predicador con Pablo","coherente","Hch 18,5"),
    ("2Cor","Ἁρέτας"): ("Damasco","mencionado","(su etnarca)","coherente","Hch 9,23-25 (huida de Damasco, sin nombrar a Aretas)"),
    ("Gal","Παῦλος"): ("—","remitente","—","coherente",""), ("Gal","Κηφᾶς"): ("Jerusalén/Antioquía","mencionado","apóstol","coherente","Hch 15; cronología discutida"),
    ("Gal","Πέτρος"): ("—","mencionado","apóstol","coherente",""), ("Gal","Ἰάκωβος"): ("Jerusalén","mencionado","hermano del Señor","coherente","Hch 15,13"),
    ("Gal","Ἰωάννης"): ("Jerusalén","mencionado","columna","coherente","Hch 3-4; 8,14"), ("Gal","Βαρναβᾶς"): ("Antioquía","mencionado","compañero","coherente","Hch 11-15"),
    ("Gal","Τίτος"): ("Jerusalén","mencionado","compañero","no comprobable",""),
    ("Flp","Παῦλος"): ("prisión (lugar no dicho)","remitente","—","no comprobable",""), ("Flp","Τιμόθεος"): ("—","remitente","hermano","coherente","Hch 16,1-3; 20,4"),
    ("Flp","Ἐπαφρόδιτος"): ("Filipos","mencionado","enviado de la iglesia","no comprobable",""), ("Flp","Εὐοδία"): ("Filipos","mencionado","—","no comprobable",""),
    ("Flp","Συντύχη"): ("Filipos","mencionado","—","no comprobable",""), ("Flp","Κλήμης"): ("Filipos","mencionado","colaborador","no comprobable",""),
    ("1Tes","Παῦλος"): ("Corinto (redacción)","remitente","—","coherente","Hch 18,5"), ("1Tes","Σιλουανός"): ("Corinto","remitente","—","coherente","Hch 17,1-18,5"),
    ("1Tes","Τιμόθεος"): ("Corinto","remitente","enviado a Tesalónica","coherente","Hch 17,14-15; 18,5"),
    ("Flm","Παῦλος"): ("prisión","remitente","—","no comprobable",""), ("Flm","Τιμόθεος"): ("—","remitente","hermano","coherente",""),
    ("Flm","Φιλήμων"): ("Colosas (por Col 4,9.17)","destinatario","colaborador","no comprobable",""), ("Flm","Ἀπφία"): ("Colosas","destinatario","hermana","no comprobable",""),
    ("Flm","Ἄρχιππος"): ("Colosas","destinatario","compañero de armas","coherente","Col 4,17"), ("Flm","Ὀνήσιμος"): ("Colosas","mencionado","esclavo de Filemón","coherente","Col 4,9"),
    ("Flm","Ἐπαφρᾶς"): ("prisión","saludado","prisionero con Pablo","coherente","Col 1,7; 4,12"), ("Flm","Μᾶρκος"): ("prisión","saludado","colaborador","coherente","Col 4,10"),
    ("Flm","Ἀρίσταρχος"): ("prisión","saludado","colaborador","coherente","Col 4,10; Hch 27,2"), ("Flm","Δημᾶς"): ("prisión","saludado","colaborador","coherente","Col 4,14"),
    ("Flm","Λουκᾶς"): ("prisión","saludado","colaborador","coherente","Col 4,14"),
    ("Ef","Παῦλος"): ("prisión","remitente","—","no comprobable",""), ("Ef","Τυχικός"): ("—","colaborador","portador","coherente","Col 4,7; Hch 20,4"),
    ("Col","Παῦλος"): ("prisión","remitente","—","no comprobable",""), ("Col","Τιμόθεος"): ("—","remitente","hermano","coherente",""),
    ("Col","Ἐπαφρᾶς"): ("Colosas","mencionado","evangelizador de Colosas","coherente","Flm 23"), ("Col","Τυχικός"): ("—","colaborador","portador","coherente","Ef 6,21; Hch 20,4"),
    ("Col","Ὀνήσιμος"): ("Colosas","colaborador","hermano","coherente","Flm 10"), ("Col","Ἀρίσταρχος"): ("prisión","saludado","prisionero con Pablo","coherente","Flm 24"),
    ("Col","Μᾶρκος"): ("prisión","saludado","primo de Bernabé","coherente","Hch 15,37-39 (Marcos con Bernabé); Flm 24"), ("Col","Βαρναβᾶς"): ("—","mencionado","primo de Marcos","coherente","Hch 15,39"),
    ("Col","Ἰοῦστος"): ("prisión","saludado","colaborador judío","no comprobable",""), ("Col","Λουκᾶς"): ("prisión","saludado","médico","coherente","Flm 24"),
    ("Col","Δημᾶς"): ("prisión","saludado","—","coherente","Flm 24"), ("Col","Νύμφα"): ("Laodicea","saludado","(iglesia en su casa)","no comprobable",""),
    ("Col","Ἄρχιππος"): ("Colosas","mencionado","ministerio","coherente","Flm 2"),
    ("2Tes","Παῦλος"): ("—","remitente","—","coherente",""), ("2Tes","Σιλουανός"): ("—","remitente","—","coherente","1 Tes 1,1"), ("2Tes","Τιμόθεος"): ("—","remitente","—","coherente","1 Tes 1,1"),
    ("1Tim","Παῦλος"): ("Macedonia (1,3)","remitente","—","no comprobable","viaje Éfeso→Macedonia dejando a Timoteo: sin correlato en Hechos"),
    ("1Tim","Τιμόθεος"): ("Éfeso","destinatario","hijo en la fe","no comprobable","Hch 19,22 lo envía a Macedonia desde Éfeso"),
    ("1Tim","Ὑμέναιος"): ("Éfeso","adversario","—","coherente","2 Tim 2,17"), ("1Tim","Ἀλέξανδρος"): ("Éfeso","adversario","—","coherente","2 Tim 4,14; Hch 19,33 (juicio)"),
    ("1Tim","Πιλᾶτος"): ("—","mencionado","—","coherente",""), ("1Tim","Πόντιος"): ("—","mencionado","—","coherente",""),
    ("2Tim","Παῦλος"): ("Roma (prisión)","remitente","—","no comprobable","2 Tim 1,17"), ("2Tim","Τιμόθεος"): ("Éfeso (4,12.19)","destinatario","hijo amado","no comprobable",""),
    ("2Tim","Λωΐς"): ("Listra","mencionado","abuela de Timoteo","no comprobable","Hch 16,1 (madre judía creyente, sin nombre)"), ("2Tim","Εὐνίκη"): ("Listra","mencionado","madre de Timoteo","coherente","Hch 16,1"),
    ("2Tim","Φύγελος"): ("Asia","adversario","—","no comprobable",""), ("2Tim","Ἑρμογένης"): ("Asia","adversario","—","no comprobable",""),
    ("2Tim","Ὀνησίφορος"): ("Éfeso/Roma","mencionado","(su casa)","no comprobable",""), ("2Tim","Ὑμέναιος"): ("—","adversario","—","coherente","1 Tim 1,20"),
    ("2Tim","Φίλητος"): ("—","adversario","—","no comprobable",""), ("2Tim","Δημᾶς"): ("Tesalónica","mencionado","desertor","coherente","Col 4,14; Flm 24 (trayectoria, sin contradicción)"),
    ("2Tim","Κρήσκης"): ("Galacia","mencionado","—","no comprobable",""), ("2Tim","Τίτος"): ("Dalmacia","mencionado","—","no comprobable",""),
    ("2Tim","Λουκᾶς"): ("Roma","mencionado","único acompañante","coherente","Col 4,14; Flm 24"), ("2Tim","Μᾶρκος"): ("—","mencionado","útil para el ministerio","coherente","Col 4,10"),
    ("2Tim","Τυχικός"): ("Éfeso","mencionado","enviado","coherente","Ef 6,21; Col 4,7"), ("2Tim","Κάρπος"): ("Tróade","mencionado","(capa y libros)","no comprobable",""),
    ("2Tim","Ἀλέξανδρος"): ("Éfeso","adversario","calderero","coherente","1 Tim 1,20"), ("2Tim","Πρίσκα"): ("Éfeso","saludado","—","coherente","Hch 18,18-19; 1 Cor 16,19"),
    ("2Tim","Ἀκύλας"): ("Éfeso","saludado","—","coherente","Hch 18,18-19"), ("2Tim","Ἔραστος"): ("Corinto","mencionado","—","coherente","Rom 16,23; Hch 19,22"),
    ("2Tim","Τρόφιμος"): ("Mileto","mencionado","dejado enfermo","no comprobable","Hch 21,29 lo sitúa en Jerusalén con Pablo; una parada en Mileto no encaja en el último viaje de Hch 20-21 (juicio)"),
    ("2Tim","Εὔβουλος"): ("Roma","saludado","—","no comprobable",""), ("2Tim","Πούδης"): ("Roma","saludado","—","no comprobable",""),
    ("2Tim","Λίνος"): ("Roma","saludado","—","no comprobable",""), ("2Tim","Κλαυδία"): ("Roma","saludado","—","no comprobable",""),
    ("2Tim","Ἰάννης"): ("—","personaje literario","—","coherente",""), ("2Tim","Ἰαμβρῆς"): ("—","personaje literario","—","coherente",""),
    ("Tit","Παῦλος"): ("—","remitente","—","no comprobable","Tit 1,5 (Creta) y 3,12 (Nicópolis): sin correlato en Hechos"), ("Tit","Τίτος"): ("Creta","destinatario","hijo","no comprobable",""),
    ("Tit","Ἀρτεμᾶς"): ("—","mencionado","enviado","no comprobable",""), ("Tit","Τυχικός"): ("—","mencionado","enviado","coherente",""),
    ("Tit","Ζηνᾶς"): ("Creta","mencionado","jurista","no comprobable",""), ("Tit","Ἀπολλῶς"): ("Creta","mencionado","—","no comprobable","Hch 18-19 lo sitúa en Éfeso y Corinto"),
    ("Heb","Τιμόθεος"): ("—","mencionado","hermano liberado","no comprobable","Heb 13,23"),
}
