# -*- coding: utf-8 -*-
"""Clasificación manual de los candidatos (tokens con mayúscula) de las colecciones de referencia del canal onomástico
(docs/canales/codigos_onomastica.md § 1 y § 4). Codificador único (enmienda 6).

Cada colección lleva una lista de reglas (prefijo, nombre_es, tipo): un candidato se asigna al nombre cuyo prefijo más
largo coincide con su forma normalizada (minúsculas, σ final unificada). Lo que no casa con ninguna regla no es nombre
de persona (lugar, pueblo, palabra común con mayúscula de comienzo de frase, título) y queda fuera del inventario.

tipo: persona (contemporánea del documento: destinatarios, colaboradores, funcionarios, herejes vivos…), historico
(personaje de la historia anterior al documento, incluidos apóstoles y emperadores difuntos), literario (personaje
de la literatura, el mito o la filosofía anteriores), biblico (AT y personajes del NT ajenos al tiempo del documento).
`historico`, `literario` y `biblico` cuentan como «famoso» (d = 1)."""

R = {}

R["Ignacio"] = [
    ("βάσσ", "Baso", "persona"), ("βούρρ", "Burro", "persona"), ("δάφν", "Dafno", "persona"), ("δαμᾶ", "Damas", "persona"),
    ("δαυείδ", "David", "biblico"), ("εὔπλ", "Euplo", "persona"), ("εὔτεκν", "Eutecno", "persona"), ("ζωτίων", "Zotión", "persona"),
    ("κρόκ", "Croco", "persona"), ("μαρία", "María (madre de Jesús)", "biblico"), ("μωύσ", "Moisés", "biblico"), ("πέτρ", "Pedro", "historico"),
    ("παύλ", "Pablo", "historico"), ("παῦλ", "Pablo", "historico"), ("πιλάτ", "Pilato", "historico"), ("ποντί", "Pilato", "historico"),
    ("πολυκάρπ", "Policarpo", "persona"), ("πολύκαρπ", "Policarpo", "persona"), ("πολύβι", "Polibio", "persona"), ("ταουΐ", "Tavía", "persona"),
    ("φίλων", "Filón (diácono)", "persona"), ("φρόντων", "Frontón", "persona"), ("ἀγαθόπο", "Agatopo", "persona"), ("ἀπολλωνί", "Apolonio", "persona"),
    ("ἄλκη", "Alce", "persona"), ("ἄτταλ", "Átalo", "persona"), ("ἡρώδ", "Herodes", "historico"), ("ἰγνάτι", "Ignacio", "persona"),
    ("ἰσαάκ", "Isaac", "biblico"), ("ἰωάνν", "Juan (apóstol)", "historico"), ("ὀνήσιμ", "Onésimo (obispo)", "persona"), ("ὀνησίμ", "Onésimo (obispo)", "persona"),
    ("ῥέῳ", "Reo", "persona"),
]

R["1Clem"] = [
    ("βίτων", "Vitón", "persona"), ("οὐαλέρι", "Valerio Vitón", "persona"), ("φορτουνάτ", "Fortunato", "persona"), ("κλαύδι", "Claudio Efebo", "persona"),
    ("ἔφηβ", "Claudio Efebo", "persona"), ("κηφᾶ", "Cefas (Pedro)", "historico"), ("πέτρ", "Pedro", "historico"), ("παύλ", "Pablo", "historico"), ("παῦλ", "Pablo", "historico"),
    ("ἀπολλώ", "Apolo (1 Cor)", "historico"),
    ("δαθάν", "Datán", "biblico"), ("δανιήλ", "Daniel", "biblico"), ("δαυείδ", "David", "biblico"), ("κάϊν", "Caín", "biblico"), ("λαβάν", "Labán", "biblico"),
    ("λώτ", "Lot", "biblico"), ("μαριάμ", "Miriam", "biblico"), ("μισαήλ", "Misael", "biblico"), ("μωϋσ", "Moisés", "biblico"), ("ναυή", "Josué hijo de Nun", "biblico"),
    ("σαούλ", "Saúl", "biblico"), ("φαραώ", "Faraón", "biblico"), ("ἀαρών", "Aarón", "biblico"), ("ἀβειρών", "Abirón", "biblico"), ("ἀζαρία", "Azarías", "biblico"),
    ("ἀνανία", "Ananías", "biblico"), ("ἄβελ", "Abel", "biblico"), ("ἐνώχ", "Henoc", "biblico"), ("ἐσθήρ", "Ester", "biblico"), ("ἑλισαι", "Eliseo", "biblico"),
    ("ἠλία", "Elías", "biblico"), ("ἰεζεκιήλ", "Ezequiel", "biblico"), ("ἰεσσαί", "Jesé", "biblico"), ("ἰουδίθ", "Judit", "biblico"), ("ἰούδα", "Judá", "biblico"),
    ("ἰσαάκ", "Isaac", "biblico"), ("ἰωνᾶ", "Jonás", "biblico"), ("ἰωσήφ", "José", "biblico"), ("ἰώβ", "Job", "biblico"), ("ῥαάβ", "Rahab", "biblico"),
    ("ὀλοφέρν", "Holofernes", "biblico"), ("δίρκ", "Dirce", "literario"), ("δαναΐδ", "Danaides", "literario"),
]

R["3Cor"] = [
    ("παῦλ", "Pablo", "historico"), ("μαρία", "María (madre de Jesús)", "biblico"), ("δαυίδ", "David", "biblico"), ("ἰωνᾶ", "Jonás", "biblico"),
    ("ἐλισαί", "Eliseo", "biblico"),
]

R["Ps-Basilio"] = [("λαῦσ", "Lauso", "persona"), ("ἀργέ", "Argeo", "persona"), ("μωσέ", "Moisés", "biblico")]

R["Ps-Clemente"] = [
    ("βαρνάβ", "Bernabé", "historico"), ("κλήμ", "Clemente", "persona"), ("πέτρ", "Pedro", "historico"), ("παῦλ", "Pablo", "historico"),
    ("σίμων", "Simón (Pedro)", "historico"), ("τιμόθε", "Timoteo", "historico"), ("ιάκωβ", "Santiago", "historico"), ("ἰακώβ", "Santiago", "historico"),
    ("ἰωάνν", "Juan", "historico"), ("θήμαρ", "Tamar", "biblico"), ("βηρσαβεέ", "Betsabé", "biblico"), ("δανιήλ", "Daniel", "biblico"), ("δαυίδ", "David", "biblico"),
    ("μωϋσ", "Moisés", "biblico"), ("σαμψών", "Sansón", "biblico"), ("σολομών", "Salomón", "biblico"), ("σωσάνν", "Susana", "biblico"), ("ἀμνών", "Amnón", "biblico"),
    ("ἐλισσαί", "Eliseo", "biblico"), ("ἡλιοῦ", "Elías", "biblico"), ("ἡσαΐ", "Isaías", "biblico"), ("ἰεζεκιήλ", "Ezequiel", "biblico"), ("ἰωσήφ", "José", "biblico"),
    ("ἰώβ", "Job", "biblico"),
]

R["Ps-Juliano"] = [
    ("βακχύλ", "Baquilo", "persona"), ("δαρεί", "Darío", "historico"), ("δημόκριτ", "Demócrito", "literario"), ("θεόφραστ", "Teofrasto", "literario"),
    ("θησε", "Teseo", "literario"), ("θαμύρ", "Tamiris", "literario"), ("κωνσταντί", "Constancio II", "historico"), ("κώνστα", "Constante", "historico"),
    ("νικομήδ", "Nicomedes", "persona"), ("πίνδαρ", "Píndaro", "literario"), ("πλάτων", "Platón", "literario"), ("πρωτέ", "Proteo", "literario"), ("πρωτεύ", "Proteo", "literario"),
    ("σάπωρ", "Sapor II", "persona"), ("σαπφώ", "Safo", "literario"), ("σιμωνίδ", "Simónides", "literario"), ("σωκράτ", "Sócrates", "literario"), ("σώπατρ", "Sópatro", "persona"),
    ("τηλεμάχ", "Telémaco", "literario"), ("τηρέ", "Tereo", "literario"), ("τυφωέ", "Tifón", "literario"), ("ἀλκίνο", "Alcínoo", "literario"), ("ἀρισταῖ", "Aristeo", "literario"),
    ("ἀριστοτέλ", "Aristóteles", "literario"), ("ἀριστοφάν", "Aristófanes", "literario"), ("ἀστυδάμ", "Astidamante", "literario"), ("ἑκάλη", "Hécale", "literario"),
    ("ἡροδότ", "Heródoto", "literario"), ("ἰάμβλιχ", "Jámblico", "persona"), ("ἰαμβλίχ", "Jámblico", "persona"), ("ἰουλιαν", "Juliano", "persona"), ("ἰοῦσ", "Ío", "literario"),
    ("ἱπποκράτ", "Hipócrates", "literario"), ("ὀδυσσ", "Odiseo", "literario"), ("οδυσσ", "Odiseo", "literario"), ("ὀρφέ", "Orfeo", "literario"), ("ὅμηρ", "Homero", "literario"),
    ("ὁμήρ", "Homero", "literario"), ("μαρσύ", "Marsias", "literario"), ("βριάρε", "Briareo", "literario"),
]

R["Ps-Ignacio"] = [
    ("βάσσ", "Baso", "persona"), ("βίτο", "Vito", "persona"), ("βασιλίδ", "Basílides", "historico"), ("βιτάλι", "Vital", "persona"), ("βούργ", "Burro", "persona"),
    ("βούρρ", "Burro", "persona"), ("γάϊ", "Gayo", "persona"), ("γαΐ", "Gayo", "persona"), ("γαυΐ", "Gavia", "persona"), ("δάφν", "Dafno", "persona"), ("δαμᾶ", "Damas", "persona"),
    ("εὐλόγι", "Eulogio", "persona"), ("εὐοδί", "Evodio", "historico"), ("εὐφανί", "Eufanio", "persona"), ("εὔπλ", "Euplo", "persona"), ("εὔτεκν", "Eutecno", "persona"),
    ("ζαρβ", "Zarbo", "persona"), ("ζωτίων", "Zotión", "persona"), ("θεόδοτ", "Teódoto", "persona"), ("θωμᾶ", "Tomás", "historico"), ("θωμᾷ", "Tomás", "historico"),
    ("κασσιαν", "Casiano", "persona"), ("κλήμ", "Clemente Romano", "historico"), ("κλεόβουλ", "Cleóbulo", "historico"), ("κρόκ", "Croco", "persona"),
    ("λουκᾶ", "Lucas", "historico"), ("λῑν", "Lino", "historico"), ("μάριν", "Maris", "persona"), ("μαρία", "María", "persona"), ("μαρίᾳ", "María", "persona"), ("μαρίαν", "María", "persona"), ("μαρίασ", "María", "persona"),
    ("μένανδρ", "Menandro (hereje)", "historico"), ("νικόλα", "Nicolás (nicolaítas)", "historico"), ("πέτρ", "Pedro", "historico"), ("παύλ", "Pablo", "historico"), ("παῦλ", "Pablo", "historico"),
    ("πιλάτ", "Pilato", "historico"), ("ποντί", "Pilato", "historico"), ("πολυκάρπ", "Policarpo", "persona"), ("πολύκαρπ", "Policarpo", "persona"), ("πολύβι", "Polibio", "persona"),
    ("σίμων", "Simón Mago", "historico"), ("τίτ", "Tito", "historico"), ("τιμόθε", "Timoteo", "historico"), ("τιμοθέ", "Timoteo", "historico"), ("φίλων", "Filón (diácono)", "persona"),
    ("φρόντων", "Frontón", "persona"), ("ἀγαθόπο", "Agatopo", "persona"), ("ἀνεγκλήτ", "Anacleto", "historico"), ("ἀπολλωνί", "Apolonio", "persona"), ("ἄλκη", "Alce", "persona"),
    ("ἄννα", "Ana (profetisa)", "biblico"), ("ἄτταλ", "Átalo", "persona"), ("ἐβίων", "Ebión", "historico"), ("ἥρων", "Herón (diácono)", "persona"), ("ἰάκωβ", "Santiago", "historico"),
    ("ἰακώβ", "Santiago", "historico"), ("ἰγνάτι", "Ignacio", "persona"), ("ἰγνατί", "Ignacio", "persona"), ("ἰωάνν", "Juan", "historico"), ("ὀνήσιμ", "Onésimo (obispo)", "persona"),
    ("ὀνησίμ", "Onésimo (obispo)", "persona"), ("ἡρῴδ", "Herodes", "historico"),
    ("δαθάν", "Datán", "biblico"), ("δανιήλ", "Daniel", "biblico"), ("δαυίδ", "David", "biblico"), ("εὔα", "Eva", "biblico"), ("ζαχαρί", "Zacarías", "biblico"), ("κάϊν", "Caín", "biblico"),
    ("κορέ", "Coré", "biblico"), ("μελχισεδ", "Melquisedec", "biblico"), ("μωσ", "Moisés", "biblico"), ("ναυῆ", "Josué hijo de Nun", "biblico"), ("σαμουήλ", "Samuel", "biblico"),
    ("σαούλ", "Saúl", "biblico"), ("σολομών", "Salomón", "biblico"), ("ἀαρών", "Aarón", "biblico"), ("ἀβεδδαδάν", "Abdadán", "biblico"), ("ἀβειρών", "Abirón", "biblico"),
    ("ἀβεσσαλώμ", "Absalón", "biblico"), ("ἄβελ", "Abel", "biblico"), ("ἐλισσαί", "Eliseo", "biblico"), ("ἠλία", "Elías", "biblico"), ("ἡλεί", "Elí", "biblico"),
    ("ἡσαΐ", "Isaías", "biblico"), ("ἰουδίθ", "Judit", "biblico"), ("ἰούδ", "Judas", "biblico"), ("ἰσαάκ", "Isaac", "biblico"), ("ἱσαάκ", "Isaac", "biblico"), ("ἰωνᾶ", "Jonás", "biblico"),
    ("ἰωσήφ", "José", "biblico"), ("ἰωσία", "Josías", "biblico"), ("ἰωσεδέκ", "Josedec", "biblico"), ("ἰώβ", "Job", "biblico"), ("ἱερεμί", "Jeremías", "biblico"), ("ὀζία", "Ozías", "biblico"),
]

R["Juliano"] = [
    ("βαβρί", "Babrio", "persona"), ("γαυδέντι", "Gaudencio", "persona"), ("γεωργί", "Jorge de Capadocia", "persona"), ("γεώργι", "Jorge de Capadocia", "persona"),
    ("γιντωνί", "Gintonio", "persona"), ("γλαύκων", "Glaucón", "literario"), ("γλαύκῳ", "Glauco", "literario"), ("δίων", "Dión", "historico"), ("δαρε", "Darío", "historico"),
    ("δεκέντι", "Decencio", "persona"), ("δηιόκ", "Deyoces", "historico"), ("δημοσθέν", "Demóstenes", "literario"), ("δημόκριτ", "Demócrito", "literario"),
    ("διογέν", "Diógenes", "literario"), ("διομήδ", "Diomedes", "literario"), ("διονύσι", "Dionisio", "persona"), ("δυνάμι", "Dinamio", "persona"), ("εὐάγρι", "Evagrio", "persona"),
    ("εὐσεβί", "Eusebia", "persona"), ("εὔμαι", "Eumeo", "literario"), ("θεμιστοκλ", "Temístocles", "historico"), ("θερσίτ", "Tersites", "literario"), ("θουκυδίδ", "Tucídides", "literario"),
    ("θράσυλλ", "Trasilo", "historico"), ("θρασύλλ", "Trasilo", "historico"), ("κάλλιπ", "Calipo", "historico"), ("κάτων", "Catón", "historico"), ("κέβητ", "Cebes", "literario"),
    ("καλλισθέν", "Calístenes", "historico"), ("καρτερί", "Carterio", "persona"), ("κινύρ", "Cíniras", "literario"), ("κλεινί", "Clinias", "literario"), ("κλεῖτ", "Clito", "historico"),
    ("κωνσταντίν", "Constantino", "historico"), ("κωνσταντῖν", "Constantino", "historico"), ("κωνσταντί", "Constancio II", "persona"), ("κωνστάντι", "Constancio II", "persona"),
    ("κώνσταντ", "Constante", "historico"), ("λάγ", "Lago", "historico"), ("λαέρτ", "Laertes", "literario"), ("λαμπρί", "Lamprias", "persona"), ("λαυρίκι", "Lauricio", "persona"),
    ("λουκιλιαν", "Luciliano", "persona"), ("λουκᾶ", "Lucas", "biblico"), ("λουππικ", "Lupicino", "persona"), ("λυκάμβ", "Licambes", "literario"), ("λυκο", "Licurgo", "historico"),
    ("λυσί", "Lisias", "literario"), ("μάξιμ", "Máximo", "persona"), ("μάρκ", "Marcos", "biblico"), ("μαγνεντί", "Magnencio", "persona"), ("μαρῖν", "Marino", "persona"),
    ("ματθαῖ", "Mateo", "biblico"), ("μουσών", "Musonio", "persona"), ("μουσωνί", "Musonio", "persona"), ("μυγδονί", "Migdonio", "persona"), ("νέρων", "Nerón", "historico"),
    ("νεβρίδι", "Nebridio", "persona"), ("νεοκλ", "Neocles", "historico"), ("νικολά", "Nicolás", "persona"), ("νικόλα", "Nicolás", "persona"), ("ξέρξ", "Jerjes", "historico"),
    ("ξενοφῶν", "Jenofonte", "literario"), ("παρμενίων", "Parmenión", "historico"), ("παύλ", "Pablo", "biblico"), ("παῦλ", "Pablo", "biblico"), ("πεντάδι", "Pentadio", "persona"),
    ("πηγάσι", "Pegasio", "persona"), ("πίνδαρ", "Píndaro", "literario"), ("πινδάρ", "Píndaro", "literario"), ("πιττακ", "Pítaco", "literario"), ("πλάτων", "Platón", "literario"),
    ("πτολεμαῖ", "Ptolomeo", "historico"), ("πτολεμαί", "Ptolomeo", "historico"), ("πυθαγόρ", "Pitágoras", "literario"), ("σαλούστι", "Salustio", "persona"), ("σαπφώ", "Safo", "literario"),
    ("σαρδαναπάλ", "Sardanápalo", "literario"), ("σελεύκ", "Seleuco", "persona"), ("σιλουαν", "Silvano (usurpador)", "persona"), ("σιμμί", "Simias", "literario"), ("σωκράτ", "Sócrates", "literario"),
    ("σωφρονίσκ", "Sofronisco", "literario"), ("σόλων", "Solón", "literario"), ("σώπατρ", "Sópatro", "persona"), ("τηλέμαχ", "Telémaco", "literario"), ("τηλεμάχ", "Telémaco", "literario"),
    ("τιβερί", "Tiberio", "historico"), ("τιθων", "Titono", "literario"), ("τίτον", "Tito", "biblico"), ("φαίδων", "Fedón", "literario"), ("φειδί", "Fidias", "literario"),
    ("φιλίππ", "Filipo II", "historico"), ("φιλώτ", "Filotas", "historico"), ("φλωρέντι", "Florencio", "persona"), ("φῆλιξ", "Félix", "persona"), ("χνοδομαρί", "Cnodomario", "persona"),
    ("χρύσιππ", "Crisipo", "literario"), ("ἀγαμέμνον", "Agamenón", "literario"), ("ἀγριππίν", "Agripina", "historico"), ("ἀθανάσι", "Atanasio", "persona"), ("ἀθανασί", "Atanasio", "persona"),
    ("ἀλέξανδρ", "Alejandro Magno", "historico"), ("ἀλεξάνδρ", "Alejandro Magno", "historico"), ("ἀμφίον", "Anfión", "literario"), ("ἀνάχαρσ", "Anacarsis", "literario"),
    ("ἀναξαγόρ", "Anaxágoras", "literario"), ("ἀντισθέν", "Antístenes", "literario"), ("ἀράξι", "Araxio", "persona"), ("ἀρείου", "Arrio", "historico"), ("ἀριστείδ", "Arístides", "historico"),
    ("ἀριστοτέλ", "Aristóteles", "literario"), ("ἀριστοφάν", "Aristófanes", "literario"), ("ἀρσάκι", "Arsacio", "persona"), ("ἀρχίλοχ", "Arquíloco", "literario"), ("ἀστυδάμ", "Astidamante", "literario"),
    ("ἀφρικαν", "Africano", "persona"), ("ἀφόβι", "Afobio", "persona"), ("ἀχιλλ", "Aquiles", "literario"), ("ἄβαρ", "Ábaris", "literario"), ("ἐπίκτητ", "Epicteto", "literario"),
    ("ἐπικούρ", "Epicuro", "literario"), ("ἑρμόλα", "Hermolao", "historico"), ("ἕκτορ", "Héctor", "literario"), ("ἡρακλ", "Heracles", "literario"), ("ἡροδότ", "Heródoto", "literario"),
    ("ἡσίοδ", "Hesíodo", "literario"), ("ἡσιόδ", "Hesíodo", "literario"), ("ἤλεκτρ", "Electra", "literario"), ("ἰαμβλίχ", "Jámblico", "historico"), ("ἰουλιαν", "Juliano", "persona"),
    ("ἰσοκράτ", "Isócrates", "literario"), ("ἱμέρι", "Himerio", "persona"), ("ἱπποκράτ", "Hipócrates", "literario"), ("ἴουλ", "Julo", "literario"), ("ὀδυσσ", "Odiseo", "literario"),
    ("ὅμηρ", "Homero", "literario"), ("ὁμήρ", "Homero", "literario"), ("ὁμηρου", "Homero", "literario"),
]

R["Basilio"] = [
    ("βάραχ", "Baraco", "persona"), ("βάσσ", "Baso", "persona"), ("βαρσούμ", "Barsumas", "persona"), ("βασίλει", "Basilio", "persona"), ("βρεττάνι", "Britanio", "persona"),
    ("βῖθ", "Vito", "persona"), ("γελασί", "Gelasio", "persona"), ("γρηγορί", "Gregorio", "persona"), ("γρηγόρι", "Gregorio", "persona"), ("δαζίζ", "Daziza", "persona"),
    ("δαφν", "Dafno", "persona"), ("δημοσθέν", "Demóstenes", "persona"), ("διάνι", "Dianio", "persona"), ("διοδώρ", "Diodoro", "persona"), ("διόδωρ", "Diodoro", "persona"),
    ("διονύσι", "Dionisio", "persona"), ("δωήκ", "Doeg", "biblico"), ("δωροθέ", "Doroteo", "persona"), ("δωρόθε", "Doroteo", "persona"), ("εὐάγρι", "Evagrio", "persona"),
    ("εὐαγρί", "Evagrio", "persona"), ("εὐδοξί", "Eudoxio", "persona"), ("εὐιππί", "Euipio", "persona"), ("εὐϊππί", "Euipio", "persona"), ("εὐνομί", "Eunomio", "persona"),
    ("εὐνόμι", "Eunomio", "persona"), ("εὐσέβ", "Eusebio", "persona"), ("εὐσεβί", "Eusebio", "persona"), ("εὐστάθι", "Eustacio", "persona"), ("εὐσταθί", "Eustacio", "persona"),
    ("ζήνων", "Zenón", "persona"), ("θαλάσσι", "Talasio", "persona"), ("θεοδώρητ", "Teodoreto", "persona"), ("θεοδώρ", "Teodoro", "persona"), ("θεόδοτ", "Teódoto", "persona"),
    ("θεόφιλ", "Teófilo", "persona"), ("θεόφραστ", "Teofrasto", "persona"), ("θρασυμάχ", "Trasímaco", "literario"), ("καλυψ", "Calipso", "literario"), ("κυριακ", "Ciríaco", "persona"),
    ("λιβάνι", "Libanio", "persona"), ("μάξιμ", "Máximo", "persona"), ("μάρι", "Maris", "persona"), ("μάρκελλ", "Marcelo", "persona"), ("μαρί", "María", "persona"),
    ("μαρκιαν", "Marciano", "persona"), ("μελέτι", "Melecio", "persona"), ("μεμνόνι", "Memnonio", "persona"), ("μωϋσ", "Moisés", "biblico"), ("νάρσ", "Narsés", "persona"),
    ("οὐεσπασιαν", "Vespasiano", "historico"), ("παρηγόρι", "Paregorio", "persona"), ("παύλ", "Pablo", "biblico"), ("παῦλ", "Pablo", "biblico"), ("πελάγι", "Pelagio", "persona"),
    ("πλάτων", "Platón", "literario"), ("πομπηϊαν", "Pompeyano", "persona"), ("πρωταγόρ", "Protágoras", "literario"), ("σαβίν", "Sabino", "persona"), ("σαβελλί", "Sabelio", "historico"),
    ("σεβήρ", "Severo", "persona"), ("σιλουαν", "Silvano", "persona"), ("σολομῶ", "Salomón", "biblico"), ("στρατήγι", "Estrategio", "persona"), ("στρατηγί", "Estrategio", "persona"),
    ("σωφρόνι", "Sofronio", "persona"), ("ταντάλ", "Tántalo", "literario"), ("τιμόθε", "Timoteo", "persona"), ("φαυστῖν", "Faustino", "persona"), ("φιρμίν", "Firmino", "persona"),
    ("φρόντων", "Frontón", "persona"), ("χοσρό", "Cosroes", "persona"), ("ἀβραάμι", "Abraamio", "persona"), ("ἀετί", "Aecio", "persona"), ("ἀθανάσι", "Atanasio", "persona"),
    ("ἀθανασί", "Atanasio", "persona"), ("ἀκτίακ", "Actiaco", "persona"), ("ἀλέξανδρ", "Alejandro", "persona"), ("ἀλεξάνδρ", "Alejandro", "persona"), ("ἀλκμαίων", "Alcmeón", "literario"),
    ("ἀπολλινάρι", "Apolinar", "persona"), ("ἀπολλιναρί", "Apolinar", "persona"), ("ἀρεί", "Arrio", "historico"), ("ἄρει", "Arrio", "historico"), ("ἀριστοτέλ", "Aristóteles", "literario"),
    ("ἀσκλήπι", "Asclepio", "persona"), ("ἄνθιμ", "Antimo", "persona"), ("ἐκδίκι", "Ecdicio", "persona"), ("ἐλπίδι", "Elpidio", "persona"), ("ἑρμογέν", "Hermógenes", "persona"),
    ("ἰάτρι", "Iatrio", "persona"), ("ἰοβῖν", "Jovino", "persona"), ("ἰούδα", "Judas", "biblico"), ("ἰσαάκ", "Isaces", "persona"), ("ἰωάνν", "Juan", "persona"),
    ("ἰωσάκ", "Josaces", "persona"), ("ἰωσήφ", "José", "biblico"), ("ἰώβ", "Job", "biblico"), ("ἱερεμί", "Jeremías", "biblico"), ("ἱππί", "Hipias", "literario"),
    ("ὀδυσσ", "Odiseo", "literario"), ("ὅμηρ", "Homero", "literario"), ("ὑμητί", "Himecio", "persona"), ("ῥεβέκκ", "Rebeca", "biblico"),
]

R["Libanio"] = [
    ("αἰακ", "Éaco", "literario"), ("αἰσχύλ", "Esquilo", "literario"), ("αἴαντ", "Áyax", "literario"), ("βάσσ", "Baso", "persona"), ("γαυδέντι", "Gaudencio", "persona"),
    ("γαϊαν", "Gayano", "persona"), ("γυμνάσι", "Gimnasio", "persona"), ("γύγ", "Giges", "historico"), ("δατιαν", "Daciano", "persona"), ("δελγ", "Delgo", "persona"),
    ("δημοσθέν", "Demóstenes", "literario"), ("διάνι", "Dianio", "persona"), ("διανί", "Dianio", "persona"), ("διονύσι", "Dionisio", "persona"), ("δουλκίτι", "Dulcicio", "persona"),
    ("εὐάγρι", "Evagrio", "persona"), ("εὐθηρί", "Euterio", "persona"), ("εὐριπίδ", "Eurípides", "literario"), ("εὐρύβατ", "Euríbato", "literario"), ("εὐσεβί", "Eusebio", "persona"),
    ("εὐφημί", "Eufemio", "persona"), ("εὔνομ", "Eunomo", "persona"), ("ζηνοβί", "Zenobio", "persona"), ("ζηνόβι", "Zenobio", "persona"), ("θαλασσί", "Talasio", "persona"),
    ("θεμιστί", "Temistio", "persona"), ("θεμιστοκλ", "Temístocles", "historico"), ("θουκυδίδ", "Tucídides", "literario"), ("ιουλιαν", "Juliano", "persona"), ("ἰουλιαν", "Juliano", "persona"),
    ("κίμων", "Cimón", "historico"), ("καλλιόπι", "Caliopio", "persona"), ("καλυκί", "Calicio", "persona"), ("καρτέρι", "Carterio", "persona"), ("κινύρ", "Cíniras", "literario"),
    ("κλεομέν", "Cleómenes", "persona"), ("κλημάτι", "Clemacio", "persona"), ("κληματί", "Clemacio", "persona"), ("κροίσ", "Creso", "historico"), ("κυρίλλ", "Cirilo", "persona"),
    ("κυρίν", "Quirino", "persona"), ("κυρῖν", "Quirino", "persona"), ("κόδρ", "Codro", "literario"), ("λεόντι", "Leoncio", "persona"), ("λουκιαν", "Luciano", "persona"),
    ("λουππίων", "Lupión", "persona"), ("λυκί", "Licio", "persona"), ("μάγν", "Magno", "persona"), ("μάξιμ", "Máximo", "persona"), ("μαξίμ", "Máximo", "persona"),
    ("μάρκελλ", "Marcelo", "persona"), ("μαρκέλλ", "Marcelo", "persona"), ("μάρκο", "Marco", "persona"), ("μάρκου", "Marco", "persona"), ("μίδ", "Midas", "literario"),
    ("μίκκαλ", "Micalo", "persona"), ("μικκάλ", "Micalo", "persona"), ("μαιορῖν", "Mayorino", "persona"), ("μακεδόνι", "Macedonio", "persona"), ("μαρσύ", "Marsias", "literario"),
    ("μελιίδ", "Melides", "persona"), ("μιλτιάδ", "Milcíades", "historico"), ("μοδέστ", "Modesto", "persona"), ("μόδεστ", "Modesto", "persona"), ("μουσών", "Musonio", "persona"),
    ("μουσωνί", "Musonio", "persona"), ("μυγδονί", "Migdonio", "persona"), ("νέστορ", "Néstor", "literario"), ("νικοκλ", "Nicocles", "persona"), ("νιρέ", "Nireo", "literario"),
    ("οίνε", "Eneo", "literario"), ("οὐρσουάλ", "Ursulo", "persona"), ("παγκράτι", "Pancracio", "persona"), ("παλαμήδ", "Palamedes", "literario"), ("πεισίστρατ", "Pisístrato", "historico"),
    ("περικλ", "Pericles", "historico"), ("πηνελόπ", "Penélope", "literario"), ("πινδάρ", "Píndaro", "literario"), ("πλάτων", "Platón", "literario"), ("πλατῶν", "Platón", "literario"),
    ("πομπηιαν", "Pompeyano", "persona"), ("πρισκιαν", "Prisciano", "persona"), ("προκοπί", "Procopio", "persona"), ("προκόπι", "Procopio", "persona"), ("σέβων", "Sebón", "persona"),
    ("σέλευκ", "Seleuco", "persona"), ("σευήρ", "Severo", "persona"), ("σευῆρ", "Severo", "persona"), ("σιμωνίδ", "Simónides", "literario"), ("σπεκτάτ", "Espectato", "persona"),
    ("στρατήγι", "Estrategio", "persona"), ("στρατηγί", "Estrategio", "persona"), ("σωκράτ", "Sócrates", "literario"), ("τρυφωνιαν", "Trifoniano", "persona"), ("φίλιππ", "Filipo", "persona"),
    ("φλωρέντι", "Florencio", "persona"), ("φλωρεντί", "Florencio", "persona"), ("φρατέρν", "Fraterno", "persona"), ("φρατἐρν", "Fraterno", "persona"), ("φρυνώνδ", "Frinondas", "literario"),
    ("φωκίων", "Foción", "historico"), ("ἀβλάβι", "Ablabio", "persona"), ("ἀκάκι", "Acacio", "persona"), ("ἀκακί", "Acacio", "persona"), ("ἀκεσί", "Acesio", "persona"),
    ("ἀλέξανδρ", "Alejandro", "persona"), ("ἀλεξάνδρ", "Alejandro", "persona"), ("ἀλβανί", "Albanio", "persona"), ("ἀλκίμ", "Alcimo", "persona"), ("ἄλκιμ", "Alcimo", "persona"),
    ("ἀμπέλι", "Ampelio", "persona"), ("ἀμπελί", "Ampelio", "persona"), ("ἀμφιάρα", "Anfiarao", "literario"), ("ἀνατολί", "Anatolio", "persona"), ("ἀνδρονίκ", "Andrónico", "persona"),
    ("ἀνδρόνικ", "Andrónico", "persona"), ("ἄνδρονίκ", "Andrónico", "persona"), ("ἀντίοχ", "Antíoco", "persona"), ("ἀντιόχ", "Antíoco", "persona"), ("ἀπελλίων", "Apelión", "persona"),
    ("ἀπρίγγι", "Apringio", "persona"), ("ἀπριγγί", "Apringio", "persona"), ("ἀράξι", "Araxio", "persona"), ("ἀραξί", "Araxio", "persona"), ("ἀρεσί", "Aresio", "persona"),
    ("ἀρισταίνετ", "Aristéneto", "persona"), ("ἀρισταινέτ", "Aristéneto", "persona"), ("ἀρσενί", "Arsenio", "persona"), ("ἀρτέμων", "Artemón", "persona"), ("ἀσκληπιάδ", "Asclepíades", "persona"),
    ("ἀτρέ", "Atreo", "literario"), ("ἀχιλλ", "Aquiles", "literario"), ("ἁρμοδί", "Harmodio", "historico"), ("ἄδμητ", "Admeto", "literario"), ("ἄρκ", "Arces", "persona"),
    ("ἐκδικί", "Ecdicio", "persona"), ("ἐλπίδι", "Elpidio", "persona"), ("ἑλέν", "Helena", "literario"), ("ἑορτί", "Heortio", "persona"), ("ἑρμιόν", "Hermíone", "literario"),
    ("ἑρμογέν", "Hermógenes", "persona"), ("ἡρακλ", "Heracles", "literario"), ("ἰταλικιαν", "Italiciano", "persona"), ("ἰόλε", "Yolao", "literario"), ("ἱέρακ", "Hierax", "persona"),
    ("ἱερί", "Hierio", "persona"), ("ἱεροκλ", "Hierocles", "persona"), ("ἱλαρί", "Hilario", "persona"), ("ἱπποκράτ", "Hipócrates", "literario"), ("ὀβοδιαν", "Obodiano", "persona"),
    ("ὀδυσσ", "Odiseo", "literario"), ("ὀλυμπί", "Olimpio", "persona"), ("ὀλύμπι", "Olimpio", "persona"), ("ὁμήρ", "Homero", "literario"), ("ὅμηρ", "Homero", "literario"),
    ("ὁνωράτ", "Honorato", "persona"), ("ὁπτάτ", "Optato", "persona"), ("ὑπερέχι", "Hiperequio", "persona"), ("ὑπερεχί", "Hiperequio", "persona"), ("ὠρίων", "Orión", "persona"),
    ("ῥωμαν", "Romano", "persona"),
]

R["Hercher"] = [
    ("αἰσχίν", "Esquines", "historico"), ("αἰσχύλ", "Esquilo", "literario"), ("αἴθρ", "Etra", "literario"), ("αὐτόλυκ", "Autólico", "persona"), ("αὐτάνδρ", "Autandro", "persona"),
    ("βάττ", "Bato", "historico"), ("βαιτύλ", "Bétilo", "persona"), ("βελλεροφόντ", "Belerofonte", "literario"), ("βερενίκ", "Berenice", "historico"), ("βιάνορ", "Bianor", "persona"),
    ("βριάρε", "Briareo", "literario"), ("βρούτ", "Bruto", "persona"), ("βροῦτ", "Bruto", "persona"), ("γέλων", "Gelón", "historico"), ("γέταν", "Getas", "persona"),
    ("γαρότ", "Garotas", "persona"), ("γηρυόν", "Gerión", "literario"), ("γλαύκων", "Glaucón", "persona"), ("γογγύλ", "Gongilo", "historico"), ("γρύλλ", "Grilo", "persona"),
    ("γύγ", "Giges", "historico"), ("γύλιππ", "Gilipo", "historico"), ("δάμων", "Damón", "persona"), ("δαέρτ", "Laertes", "literario"), ("δαμάσιππ", "Damasipo", "persona"),
    ("δαμάστ", "Damastes", "persona"), ("δαρεῖ", "Darío", "historico"), ("δημοτέλ", "Demóteles", "persona"), ("δημότελ", "Demóteles", "persona"), ("διβάν", "Dibano", "persona"),
    ("διογέν", "Diógenes", "persona"), ("διόγεν", "Diógenes", "persona"), ("διομήδ", "Diomedes", "literario"), ("διονύσι", "Dionisio", "historico"), ("διονυσί", "Dionisio", "historico"),
    ("διοπείθ", "Diopites", "historico"), ("δολοβέλλ", "Dolabela", "persona"), ("δολοϐέλλ", "Dolabela", "persona"), ("δορυμέν", "Doríménes", "persona"), ("δρωπίδ", "Drópidas", "persona"),
    ("δυκῖν", "Ducino", "persona"), ("δόρκων", "Dorcón", "persona"), ("εὐβούλ", "Eubulo", "persona"), ("εὔβουλ", "Eubulo", "persona"), ("εὐην", "Eveno", "persona"),
    ("εὐθύδαμ", "Eutidamo", "persona"), ("εὐκλείδ", "Euclides", "persona"), ("εὐκράτ", "Eucrates", "persona"), ("εὐξίθε", "Euxíteo", "persona"), ("εὐριπίδ", "Eurípides", "persona"),
    ("εὐρυπτόλεμ", "Euriptólemo", "persona"), ("εὐρυτίων", "Euritión", "literario"), ("εὐφορίων", "Euforión", "persona"), ("εὔφρον", "Eufrón", "persona"), ("ζεύξιδ", "Zeuxis", "persona"),
    ("θεαγόρ", "Teágoras", "persona"), ("θεαν", "Teano", "persona"), ("θεμιστοκλ", "Temístocles", "persona"), ("θεμιστόκλ", "Temístocles", "persona"), ("θεόδωρ", "Teodoro", "persona"),
    ("θεόπομπ", "Teopompo", "persona"), ("θεότιμ", "Teótimo", "persona"), ("θησέ", "Teseo", "literario"), ("θράσων", "Trasón", "persona"), ("κάλλαισχρ", "Calescro", "persona"),
    ("κάσσι", "Casio", "persona"), ("κασσί", "Casio", "persona"), ("κέβη", "Cebes", "persona"), ("κέκροπ", "Cécrope", "literario"), ("κίκερμ", "Cicermo", "persona"),
    ("κίρκ", "Circe", "literario"), ("καλλία", "Calias", "persona"), ("καλλιππίδ", "Calípides", "persona"), ("καλλισθέν", "Calístenes", "persona"), ("κηφισοφῶν", "Cefisofonte", "persona"),
    ("κλέαρχ", "Clearco", "persona"), ("κλεάρχ", "Clearco", "persona"), ("κλέλομβροτ", "Cleómbroto", "persona"), ("κλεόμβροτ", "Cleómbroto", "persona"), ("κλίτων", "Clitón", "persona"),
    ("κλείδ", "Clides", "persona"), ("κλεαινέτ", "Cleéneta", "persona"), ("κλεαρίστ", "Clearista", "persona"), ("κλεινί", "Clinias", "persona"), ("κλεισθέν", "Clístenes", "persona"),
    ("κλεοφάντ", "Cleofanto", "persona"), ("κλεόφαντ", "Cleofanto", "persona"), ("κλεόδικ", "Cleódico", "persona"), ("κλεόμεδ", "Cleomedonte", "persona"), ("κόνν", "Conno", "persona"),
    ("κόνων", "Conón", "historico"), ("κότυ", "Cotis", "historico"), ("κράτησ", "Crates", "persona"), ("κρίτων", "Critón", "persona"), ("κρατίν", "Cratino", "persona"),
    ("κρατησίπολ", "Cratesípolis", "persona"), ("κρατησιπόλ", "Cratesípolis", "persona"), ("κρεσφόντ", "Cresfontes", "literario"), ("κριτοβούλ", "Critobulo", "persona"),
    ("κρωβύλ", "Cróbilo", "persona"), ("κρῖνι", "Crinis", "persona"), ("κτήσιππ", "Ctesipo", "persona"), ("κυνεγείρ", "Cinegiro", "historico"), ("κῦρ", "Ciro", "historico"),
    ("κύρῳ", "Ciro", "historico"), ("λάκριτ", "Lácrito", "persona"), ("λακρίτ", "Lácrito", "persona"), ("λέαγρ", "Leagro", "persona"), ("λαδίκ", "Ladice", "persona"),
    ("λακρατίδ", "Lacrátidas", "persona"), ("λακύδ", "Lácides", "persona"), ("λαμπροκλ", "Lamprocles", "persona"), ("λαπρέπ", "Laprepes", "persona"), ("λασθένει", "Lastenia", "persona"),
    ("λεωβώτ", "Leobotes", "persona"), ("λεωδάμ", "Leodamante", "persona"), ("λεωνίδ", "Leónidas", "historico"), ("λιογέν", "Diógenes", "persona"), ("λυκῖν", "Licino", "persona"),
    ("λυσία", "Lisias", "persona"), ("λυσίκλ", "Lisicles", "persona"), ("λυσικλ", "Lisicles", "persona"), ("λυσικράτ", "Lisícrates", "persona"), ("λυσιμάχ", "Lisímaco", "persona"),
    ("λύσανδρ", "Lisandro", "historico"), ("λύσιδ", "Lisis", "persona"), ("λῦσι", "Lisis", "persona"), ("λυσῖν", "Lisino", "persona"), ("μάξον", "Maxón", "persona"),
    ("μέλητ", "Meleto", "persona"), ("μελήτ", "Meleto", "persona"), ("μένυλλ", "Menilo", "persona"), ("μέσατ", "Mésato", "persona"), ("μίκαν", "Mica", "persona"),
    ("μίνω", "Minos", "literario"), ("μαρδονί", "Mardonio", "historico"), ("μαρδοχαῖ", "Mardoqueo", "biblico"), ("μείδων", "Midón", "persona"), ("μεγακλ", "Megacles", "persona"),
    ("μελέαγρ", "Meleagro", "literario"), ("μενοικέ", "Meneceo", "persona"), ("μηνοδώρ", "Menodoro", "persona"), ("μηνόδωρ", "Menodoro", "persona"), ("μητροβί", "Metrobio", "persona"),
    ("μνήσων", "Mnesón", "persona"), ("μναστορίδ", "Mnastóridas", "persona"), ("μοίριδ", "Meris", "persona"), ("μυρτ", "Mirto", "persona"), ("μόλων", "Molón", "persona"),
    ("νέστορ", "Néstor", "literario"), ("νίκαρχ", "Nicarco", "persona"), ("νικάρχ", "Nicarco", "persona"), ("νεοκλ", "Neocles", "persona"), ("νεοπτολέμ", "Neoptólemo", "literario"),
    ("νηλέ", "Neleo", "literario"), ("νικία", "Nicias", "persona"), ("νικοκλ", "Nicocles", "persona"), ("νικόκλ", "Nicocles", "persona"), ("νιόβ", "Níobe", "literario"),
    ("ξέρξ", "Jerjes", "historico"), ("ξανθίππ", "Jantipa", "persona"), ("ξενοφῶν", "Jenofonte", "persona"), ("πίνδαρ", "Píndaro", "literario"), ("παμφίλ", "Pánfilo", "persona"),
    ("πασίων", "Pasión", "persona"), ("παυρόλ", "Paurolas", "persona"), ("παυσανί", "Pausanias", "persona"), ("πεισίστρατ", "Pisístrato", "historico"), ("πεισιστράτ", "Pisístrato", "historico"),
    ("περίανδρ", "Periandro", "historico"), ("περίλα", "Perilao", "persona"), ("περιλά", "Perilao", "persona"), ("περίσθεν", "Perístenes", "persona"), ("περδίκκ", "Perdicas", "historico"),
    ("περικλ", "Pericles", "historico"), ("πηνελόπ", "Penélope", "literario"), ("πλάτων", "Platón", "persona"), ("ποδάρκ", "Podarces", "literario"), ("πολυκράτ", "Polícrates", "historico"),
    ("πολύγνωτ", "Polignoto", "persona"), ("πολύδευκ", "Pólux", "literario"), ("πολύκλειτ", "Policleto", "persona"), ("πολύξεν", "Polixeno", "persona"), ("προδίκ", "Pródico", "persona"),
    ("πρόδικ", "Pródico", "persona"), ("προνάπ", "Pronapes", "persona"), ("πρωτίδ", "Prótidas", "persona"), ("πρωταγόρ", "Protágoras", "persona"), ("πτολεμαί", "Ptolomeo", "historico"),
    ("πυθαγόρ", "Pitágoras", "literario"), ("πυλάδ", "Pílades", "literario"), ("πύθων", "Pitón", "persona"), ("σίκινν", "Sicino", "historico"), ("σίμων", "Simón", "persona"),
    ("σακεσφόρ", "Sacesforo", "persona"), ("σαμέα", "Sameas", "persona"), ("σαρδαναπάλλ", "Sardanápalo", "literario"), ("σειλην", "Sileno", "literario"), ("σεύθ", "Seutes", "historico"),
    ("σιμμί", "Simias", "persona"), ("σοφοκλ", "Sófocles", "persona"), ("σοφόκλ", "Sófocles", "persona"), ("σπεύσιππ", "Espeusipo", "persona"), ("σπευσίππ", "Espeusipo", "persona"),
    ("στησίχορ", "Estesícoro", "persona"), ("στησιχόρ", "Estesícoro", "persona"), ("στράτιππ", "Estratipo", "persona"), ("στρατολά", "Estratolao", "persona"), ("συλέ", "Sileo", "persona"),
    ("σωκράτ", "Sócrates", "persona"), ("σωκρατην", "Sócrates", "persona"), ("σώκρατ", "Sócrates", "persona"), ("σωφρονίσκ", "Sofronisco", "persona"), ("σώνικ", "Sónico", "persona"),
    ("σῖμον", "Simón", "persona"), ("τήλεφ", "Télefo", "literario"), ("τίβι", "Tibio", "persona"), ("τιβί", "Tibio", "persona"), ("τίμαι", "Timeo", "persona"),
    ("τίμανδρ", "Timandro", "persona"), ("τίμων", "Timón", "persona"), ("τελεσίππ", "Telesipa", "persona"), ("τερψίων", "Terpsión", "persona"), ("τεῦκρ", "Teucro", "persona"),
    ("τεύκρ", "Teucro", "persona"), ("τηλέγον", "Telégono", "literario"), ("τιθων", "Titono", "literario"), ("τιμοθέ", "Timoteo", "persona"), ("τιμόμαχ", "Timómaco", "persona"),
    ("τισίνικ", "Tisínico", "persona"), ("τυνδάρε", "Tindáreo", "literario"), ("φάλαρι", "Fálaris", "persona"), ("φαλάριδ", "Fálaris", "persona"), ("φαίδιμ", "Fedimo", "persona"),
    ("φαίδων", "Fedón", "persona"), ("φαιδρί", "Fedrias", "persona"), ("φαῖδρ", "Fedro", "persona"), ("φιλίππ", "Filipo II", "historico"), ("φιλιστίων", "Filistión", "persona"),
    ("φιλοδήμ", "Filodemo", "persona"), ("φιλόδημ", "Filodemo", "persona"), ("φιλοστέφαν", "Filostéfano", "persona"), ("φιλοστεφάν", "Filostéfano", "persona"), ("φυλλίδ", "Fílide", "literario"),
    ("χάρυβδ", "Caribdis", "literario"), ("χαιρεφῶν", "Querefonte", "persona"), ("χαρίκλ", "Caricles", "persona"), ("χαρικλ", "Caricles", "persona"), ("χιονίδ", "Quiónides", "persona"),
    ("ἀγάθων", "Agatón", "persona"), ("ἀγέμορτ", "Agemorto", "persona"), ("ἀγησιλά", "Agesilao", "historico"), ("ἀθηνοδώρ", "Atenodoro", "persona"), ("ἀκύλ", "Aquila", "persona"),
    ("ἀλέξανδρ", "Alejandro Magno", "historico"), ("ἀλεξάνδρ", "Alejandro Magno", "historico"), ("ἀλἑξανδρ", "Alejandro Magno", "historico"), ("ἀλκέτ", "Alcetas", "persona"),
    ("ἀλκιβιάδ", "Alcibíades", "historico"), ("ἀλκμεωνίδ", "Alcmeónidas", "persona"), ("ἀλκυονέ", "Alcioneo", "literario"), ("ἀμάν", "Amán", "biblico"), ("ἀμαδάθ", "Hamedata", "biblico"),
    ("ἀμεινί", "Aminias", "persona"), ("ἀμφία", "Anfias", "persona"), ("ἀμύντ", "Amintas", "historico"), ("ἀνάχαρσ", "Anacarsis", "persona"), ("ἀναχάρσ", "Anacarsis", "persona"),
    ("ἀντίοχ", "Antíoco", "persona"), ("ἀντίπατρ", "Antípatro", "historico"), ("ἀντιπάτρ", "Antípatro", "historico"), ("ἀντίσθεν", "Antístenes", "persona"), ("ἀντισθέν", "Antístenes", "persona"),
    ("ἀνταγόρ", "Antágoras", "persona"), ("ἀντιγέν", "Antígenes", "persona"), ("ἀντιμήδ", "Antimedes", "persona"), ("ἀνύτ", "Ánito", "persona"), ("ἄνυτ", "Ánito", "persona"),
    ("ἀπολλόδωρ", "Apolodoro", "persona"), ("ἀρίστιππ", "Aristipo", "persona"), ("ἀριστίππ", "Aristipo", "persona"), ("ἀρισταίνετ", "Aristéneto", "persona"), ("ἀριστείδ", "Arístides", "persona"),
    ("ἀριστειδ", "Arístides", "persona"), ("ἀριστοδήμ", "Aristodemo", "persona"), ("ἀριστομάχ", "Aristómaco", "persona"), ("ἀριστομέν", "Aristómenes", "persona"), ("ἀριστοφάν", "Aristófanes", "persona"),
    ("ἀριστοφῶν", "Aristofonte", "persona"), ("ἀρτάβαζ", "Artabazo", "historico"), ("ἀρταβάζ", "Artabazo", "historico"), ("ἀρταξέρξ", "Artajerjes", "persona"), ("ἀρχέλα", "Arquelao", "historico"),
    ("ἀρχελά", "Arquelao", "historico"), ("ἀρχέπολ", "Arquépolis", "persona"), ("ἀρχεδήμ", "Arquedemo", "persona"), ("ἀρχύτ", "Arquitas", "persona"), ("ἀρύββ", "Aribas", "historico"),
    ("ἄβαρ", "Ábaris", "literario"), ("ἄδμητ", "Admeto", "historico"), ("ἀδμήτ", "Admeto", "historico"), ("ἄδραστ", "Adrasto", "literario"), ("ἄλκηστ", "Alcestis", "literario"),
    ("ἐπιθέρσ", "Epiterses", "persona"), ("ἐπικράτ", "Epícrates", "persona"), ("ἐσθῆρ", "Ester", "biblico"), ("ἐχεκράτ", "Equécrates", "persona"), ("ἐχεκρατίδ", "Equecrátidas", "persona"),
    ("ἑρμεία", "Hermias", "persona"), ("ἑρμογέν", "Hermógenes", "persona"), ("ἑρμοδώρ", "Hermodoro", "persona"), ("ἑρμόδωρ", "Hermodoro", "persona"), ("ἑρμοκλ", "Hermocles", "persona"),
    ("ἑρμοκράτ", "Hermócrates", "persona"), ("ἡγήσιππ", "Hegesipo", "persona"), ("ἡρακλείδ", "Heraclides", "persona"), ("ἡρόδοτ", "Heródoto", "literario"), ("ἡσίοδ", "Hesíodo", "literario"),
    ("ἱέρων", "Hierón", "historico"), ("ἱπποκόων", "Hipocoonte", "literario"), ("ὀδυσσ", "Odiseo", "literario"), ("ὅμηρ", "Homero", "literario"), ("ῥαδάμανθ", "Radamantis", "literario"),
    ("ἁβρώνιχ", "Habrónico", "persona"), ("ἡρακλ", "Heracles", "literario"),
]
